-- ============================================================================
-- Migration: Sheet Metal Lookup Tables -- batch 2 staging (11 files)
-- Purpose: Lands 11 more Lookup Tables exports into the same lossless
--          staging table earlier migrations (479/482/483/484/485) created.
--          See migration 479's header for the staging/promotion
--          architecture. Combined into one migration since every file here
--          is small and each row documents its own no-consumer reasoning in
--          its `notes` column (checked individually against this app's real
--          code before staging -- see project memory
--          project_manufacturing_intelligence_data_reconciliation.md for
--          the full per-file findings).
--
--          10 of 11 files are progressive-die/deep-draw/CNC-tooling
--          reference-only (no consumer in this app, which does laser +
--          press-brake + turret + waterjet + deburr on flat sheet only).
--          ONE file -- freightRates.json -- is a separate, higher-
--          significance finding: this app previously had a FABRICATED flat
--          freight rate ($3.00/kg, invented, no source) that migration 389
--          explicitly removed as an anti-pattern violation. This export has
--          REAL region-pair rates that could replace it -- but per that same
--          root-cause standard, nothing here is auto-wired into
--          packaging_logistics_cost_records. That decision needs the user's
--          explicit sign-off, never an automatic reintroduction.
-- Author: Principal Engineering Team
-- Date: 2026-08-19
-- Version: 1.0.0
-- ============================================================================

INSERT INTO sm_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('lookup_table', 'USA', '2026-03', 'burnProfileRate:50.8', '0.01', 'CostPerLength', 'Oxyfuel/plasma thick-plate rate ($/mm) by thickness bracket -- no cost engine exists for this process in this app', '{"plateThicknessMm": 50.8, "rateUsdPerMm": 0.01}'::jsonb),
('lookup_table', 'USA', '2026-03', 'burnProfileRate:88.9', '0.01', 'CostPerLength', 'Oxyfuel/plasma thick-plate rate ($/mm) by thickness bracket -- no cost engine exists for this process in this app', '{"plateThicknessMm": 88.9, "rateUsdPerMm": 0.01}'::jsonb),
('lookup_table', 'USA', '2026-03', 'burnProfileRate:152.4', '0.01', 'CostPerLength', 'Oxyfuel/plasma thick-plate rate ($/mm) by thickness bracket -- no cost engine exists for this process in this app', '{"plateThicknessMm": 152.4, "rateUsdPerMm": 0.01}'::jsonb),
('lookup_table', 'USA', '2026-03', 'burnProfileRate:25400.0', '0.01', 'CostPerLength', 'Oxyfuel/plasma thick-plate rate ($/mm) by thickness bracket -- no cost engine exists for this process in this app', '{"plateThicknessMm": 25400.0, "rateUsdPerMm": 0.01}'::jsonb),
('lookup_table', 'USA', '2026-03', 'camUnitSizes:1000Series', '543.0', 'Mass', 'Progressive-die CAM unit tooling dimensions -- this app has no progressive-die support', '{"camIdent": "1000Series", "camFaceWidthMm": 1000.0, "camFaceHeightMm": 210.0, "camUnitOverhangMm": 200.0, "camUnitWidthMm": 1000.0, "camUnitLengthMm": 370.0, "camUnitShutHeightMm": 385.0, "camUnitWeightKg": 543.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'camUnitSizes:1200Series', '733.0', 'Mass', 'Progressive-die CAM unit tooling dimensions -- this app has no progressive-die support', '{"camIdent": "1200Series", "camFaceWidthMm": 1200.0, "camFaceHeightMm": 210.0, "camUnitOverhangMm": 200.0, "camUnitWidthMm": 1200.0, "camUnitLengthMm": 370.0, "camUnitShutHeightMm": 385.0, "camUnitWeightKg": 733.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'camUnitSizes:150Series', '89.0', 'Mass', 'Progressive-die CAM unit tooling dimensions -- this app has no progressive-die support', '{"camIdent": "150Series", "camFaceWidthMm": 190.0, "camFaceHeightMm": 150.0, "camUnitOverhangMm": 0.0, "camUnitWidthMm": 190.0, "camUnitLengthMm": 398.0, "camUnitShutHeightMm": 300.0, "camUnitWeightKg": 89.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'camUnitSizes:300Series', '222.0', 'Mass', 'Progressive-die CAM unit tooling dimensions -- this app has no progressive-die support', '{"camIdent": "300Series", "camFaceWidthMm": 400.0, "camFaceHeightMm": 180.0, "camUnitOverhangMm": 0.0, "camUnitWidthMm": 400.0, "camUnitLengthMm": 479.0, "camUnitShutHeightMm": 375.0, "camUnitWeightKg": 222.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'camUnitSizes:600Series', '307.0', 'Mass', 'Progressive-die CAM unit tooling dimensions -- this app has no progressive-die support', '{"camIdent": "600Series", "camFaceWidthMm": 600.0, "camFaceHeightMm": 210.0, "camUnitOverhangMm": 200.0, "camUnitWidthMm": 600.0, "camUnitLengthMm": 370.0, "camUnitShutHeightMm": 385.0, "camUnitWeightKg": 307.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'camUnitSizes:800Series', '422.0', 'Mass', 'Progressive-die CAM unit tooling dimensions -- this app has no progressive-die support', '{"camIdent": "800Series", "camFaceWidthMm": 800.0, "camFaceHeightMm": 210.0, "camUnitOverhangMm": 200.0, "camUnitWidthMm": 800.0, "camUnitLengthMm": 370.0, "camUnitShutHeightMm": 385.0, "camUnitWeightKg": 422.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'cncMillingRates:64516.0', '21505.0', 'Rate', 'CNC milling profiling/pocketing rate (mm2/hr) by area bracket -- this app''s cost-cnc-engine.ts uses a volume-removal-rate (MRR, mm3/min) physics model instead; different methodology, not a gap', '{"areaMm2": 64516.0, "profilingRateMm2PerHr": 21505.0, "pocketingRateMm2PerHr": 21505.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'cncMillingRates:161290.0', '25602.0', 'Rate', 'CNC milling profiling/pocketing rate (mm2/hr) by area bracket -- this app''s cost-cnc-engine.ts uses a volume-removal-rate (MRR, mm3/min) physics model instead; different methodology, not a gap', '{"areaMm2": 161290.0, "profilingRateMm2PerHr": 25602.0, "pocketingRateMm2PerHr": 25602.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'cncMillingRates:322580.0', '31625.0', 'Rate', 'CNC milling profiling/pocketing rate (mm2/hr) by area bracket -- this app''s cost-cnc-engine.ts uses a volume-removal-rate (MRR, mm3/min) physics model instead; different methodology, not a gap', '{"areaMm2": 322580.0, "profilingRateMm2PerHr": 31625.0, "pocketingRateMm2PerHr": 31625.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'cncMillingRates:645160.0', '41356.0', 'Rate', 'CNC milling profiling/pocketing rate (mm2/hr) by area bracket -- this app''s cost-cnc-engine.ts uses a volume-removal-rate (MRR, mm3/min) physics model instead; different methodology, not a gap', '{"areaMm2": 645160.0, "profilingRateMm2PerHr": 41356.0, "pocketingRateMm2PerHr": 41356.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'cncMillingRates:967740.0', '48876.0', 'Rate', 'CNC milling profiling/pocketing rate (mm2/hr) by area bracket -- this app''s cost-cnc-engine.ts uses a volume-removal-rate (MRR, mm3/min) physics model instead; different methodology, not a gap', '{"areaMm2": 967740.0, "profilingRateMm2PerHr": 48876.0, "pocketingRateMm2PerHr": 48876.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'cncMillingRates:1612900.0', '53763.0', 'Rate', 'CNC milling profiling/pocketing rate (mm2/hr) by area bracket -- this app''s cost-cnc-engine.ts uses a volume-removal-rate (MRR, mm3/min) physics model instead; different methodology, not a gap', '{"areaMm2": 1612900.0, "profilingRateMm2PerHr": 53763.0, "pocketingRateMm2PerHr": 53763.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'cncMillingRates:1935480.0', '59737.0', 'Rate', 'CNC milling profiling/pocketing rate (mm2/hr) by area bracket -- this app''s cost-cnc-engine.ts uses a volume-removal-rate (MRR, mm3/min) physics model instead; different methodology, not a gap', '{"areaMm2": 1935480.0, "profilingRateMm2PerHr": 59737.0, "pocketingRateMm2PerHr": 59737.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'cncMillingRates:2258060.0', '67204.0', 'Rate', 'CNC milling profiling/pocketing rate (mm2/hr) by area bracket -- this app''s cost-cnc-engine.ts uses a volume-removal-rate (MRR, mm3/min) physics model instead; different methodology, not a gap', '{"areaMm2": 2258060.0, "profilingRateMm2PerHr": 67204.0, "pocketingRateMm2PerHr": 67204.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'cncMillingRates:3225800.0', '67204.0', 'Rate', 'CNC milling profiling/pocketing rate (mm2/hr) by area bracket -- this app''s cost-cnc-engine.ts uses a volume-removal-rate (MRR, mm3/min) physics model instead; different methodology, not a gap', '{"areaMm2": 3225800.0, "profilingRateMm2PerHr": 67204.0, "pocketingRateMm2PerHr": 67204.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'cncMillingRates:3870960.0', '70126.0', 'Rate', 'CNC milling profiling/pocketing rate (mm2/hr) by area bracket -- this app''s cost-cnc-engine.ts uses a volume-removal-rate (MRR, mm3/min) physics model instead; different methodology, not a gap', '{"areaMm2": 3870960.0, "profilingRateMm2PerHr": 70126.0, "pocketingRateMm2PerHr": 70126.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'coatingCostTable:Nitride:S7', '0.23', 'CostPerMass', 'Progressive-die tool coating cost ($/kg) by coating type/tool material -- this app has no progressive-die tooling cost model', '{"coatingCostUsdPerKg": 0.23, "coatingType": "Nitride", "toolMaterial": "S7"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'coatingCostTable:Teflon:S7', '0.41', 'CostPerMass', 'Progressive-die tool coating cost ($/kg) by coating type/tool material -- this app has no progressive-die tooling cost model', '{"coatingCostUsdPerKg": 0.41, "coatingType": "Teflon", "toolMaterial": "S7"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'coatingCostTable:CVD:D2', '3.4', 'CostPerMass', 'Progressive-die tool coating cost ($/kg) by coating type/tool material -- this app has no progressive-die tooling cost model', '{"coatingCostUsdPerKg": 3.4, "coatingType": "CVD", "toolMaterial": "D2"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:bendCamUnit:lessThan10inches', '1700.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "bendCamUnit", "model": "lessThan10inches", "sizeMm": null, "costUsd": 1700.0, "weightKg": 89.0, "machiningHours": 0.5, "wireEdmHours": 0.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:camStripperSpool', '40.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "camStripperSpool", "model": null, "sizeMm": null, "costUsd": 40.0, "weightKg": 0.25, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:camUnit:1000Series', '13400.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "camUnit", "model": "1000Series", "sizeMm": 1000.0, "costUsd": 13400.0, "weightKg": 543.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:camUnit:1200Series', '17535.6', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "camUnit", "model": "1200Series", "sizeMm": 1200.0, "costUsd": 17535.6, "weightKg": 733.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:camUnit:150Series', '1700.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "camUnit", "model": "150Series", "sizeMm": 190.0, "costUsd": 1700.0, "weightKg": 89.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:camUnit:300Series', '3500.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "camUnit", "model": "300Series", "sizeMm": 400.0, "costUsd": 3500.0, "weightKg": 222.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:camUnit:600Series', '7700.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "camUnit", "model": "600Series", "sizeMm": 600.0, "costUsd": 7700.0, "weightKg": 307.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:camUnit:800Series', '10500.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "camUnit", "model": "800Series", "sizeMm": 800.0, "costUsd": 10500.0, "weightKg": 422.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:coilSpring', '15.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "coilSpring", "model": null, "sizeMm": null, "costUsd": 15.0, "weightKg": null, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:counterSinkRetainerStandard', '75.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "counterSinkRetainerStandard", "model": null, "sizeMm": null, "costUsd": 75.0, "weightKg": 3.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:counterSinkStandard', '125.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "counterSinkStandard", "model": null, "sizeMm": null, "costUsd": 125.0, "weightKg": 0.5, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:dieButton', '125.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "dieButton", "model": null, "sizeMm": null, "costUsd": 125.0, "weightKg": 0.5, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:gasSpring', '75.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "gasSpring", "model": null, "sizeMm": null, "costUsd": 75.0, "weightKg": 0.25, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:gasSpringFlanged', '125.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "gasSpringFlanged", "model": null, "sizeMm": null, "costUsd": 125.0, "weightKg": 0.25, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:guidePinAssy:large', '480.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "guidePinAssy", "model": "large", "sizeMm": 76.2, "costUsd": 480.0, "weightKg": 20.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:guidePinAssy:medium', '400.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "guidePinAssy", "model": "medium", "sizeMm": 63.5, "costUsd": 400.0, "weightKg": 15.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:guidePinAssy:small', '360.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "guidePinAssy", "model": "small", "sizeMm": 50.8, "costUsd": 360.0, "weightKg": 10.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:keeperBlock', '50.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "keeperBlock", "model": null, "sizeMm": null, "costUsd": 50.0, "weightKg": 1.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:partExitSensor', '206.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "partExitSensor", "model": null, "sizeMm": null, "costUsd": 206.0, "weightKg": null, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:piercePunchRetainerStandard', '75.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "piercePunchRetainerStandard", "model": null, "sizeMm": null, "costUsd": 75.0, "weightKg": 3.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:piercePunchStandard', '125.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "piercePunchStandard", "model": null, "sizeMm": null, "costUsd": 125.0, "weightKg": 0.5, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:pilotPin', '5.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "pilotPin", "model": null, "sizeMm": null, "costUsd": 5.0, "weightKg": null, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:pitchSensor', '75.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "pitchSensor", "model": null, "sizeMm": null, "costUsd": 75.0, "weightKg": null, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:shavePunchStandard', '125.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "shavePunchStandard", "model": null, "sizeMm": null, "costUsd": 125.0, "weightKg": 0.5, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:shutterPinAssy', '8.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "shutterPinAssy", "model": null, "sizeMm": null, "costUsd": 8.0, "weightKg": null, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:stamp', '100.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "stamp", "model": null, "sizeMm": null, "costUsd": 100.0, "weightKg": 0.25, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:startPin', '10.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "startPin", "model": null, "sizeMm": null, "costUsd": 10.0, "weightKg": 0.13, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:stockLifterBushing', '35.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "stockLifterBushing", "model": null, "sizeMm": null, "costUsd": 35.0, "weightKg": 0.13, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:stockLifterPin', '46.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "stockLifterPin", "model": null, "sizeMm": null, "costUsd": 46.0, "weightKg": 0.13, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:stripperGuidePinAssy', '100.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "stripperGuidePinAssy", "model": null, "sizeMm": null, "costUsd": 100.0, "weightKg": 2.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:stripperPinAssy', '5.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "stripperPinAssy", "model": null, "sizeMm": null, "costUsd": 5.0, "weightKg": 0.13, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:tappingUnit', '10379.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "tappingUnit", "model": null, "sizeMm": null, "costUsd": 10379.0, "weightKg": 10.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:tappingUnitIncrementalCosts', '7784.25', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "tappingUnitIncrementalCosts", "model": null, "sizeMm": null, "costUsd": 7784.25, "weightKg": 1.0, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:tappingUnitTravelCostPerMM', '6.02', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "tappingUnitTravelCostPerMM", "model": null, "sizeMm": null, "costUsd": 6.02, "weightKg": null, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:tapStandard', '15.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "tapStandard", "model": null, "sizeMm": null, "costUsd": 15.0, "weightKg": 0.05, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:thrustKey', '6.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "thrustKey", "model": null, "sizeMm": null, "costUsd": 6.0, "weightKg": null, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'componentStandardCosts:wearPlate', '10.0', 'Currency', 'Progressive-die tooling component standard cost (springs, guide pins, cam units, tapping units, etc.) -- this app has no progressive-die tooling cost model', '{"name": "wearPlate", "model": null, "sizeMm": null, "costUsd": 10.0, "weightKg": 0.13, "machiningHours": null, "wireEdmHours": null}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:12.7', '1.0', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 12.7, "factorK": 1.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:25.4', '1.0', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 25.4, "factorK": 1.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:38.1', '1.5', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 38.1, "factorK": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:50.8', '1.5', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 50.8, "factorK": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:76.2', '1.75', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 76.2, "factorK": 1.75}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:101.6', '2.0', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 101.6, "factorK": 2.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:152.4', '2.5', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 152.4, "factorK": 2.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:203.2', '2.75', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 203.2, "factorK": 2.75}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:254.0', '3.0', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 254.0, "factorK": 3.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:304.8', '3.25', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 304.8, "factorK": 3.25}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:355.6', '3.5', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 355.6, "factorK": 3.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:406.4', '3.75', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 406.4, "factorK": 3.75}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:457.2', '4.0', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 457.2, "factorK": 4.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:508.0', '4.25', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 508.0, "factorK": 4.25}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:558.8', '4.5', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 558.8, "factorK": 4.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'drawForceFactor:609.6', '4.75', NULL, 'Deep-draw force scaling factor K by form depth -- this app has no deep-drawing/forming process', '{"formDepthMm": 609.6, "factorK": 4.75}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:APA_APA', '1.1', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "APA_APA", "apaUsdPerKg": 1.1, "euUsdPerKg": 1.1, "naUsdPerKg": 1.1, "saUsdPerKg": 1.1}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:EU_EU', '1.1', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "EU_EU", "apaUsdPerKg": 1.1, "euUsdPerKg": 1.1, "naUsdPerKg": 1.1, "saUsdPerKg": 1.1}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:NA_NALand', '1.1', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "NA_NALand", "apaUsdPerKg": 1.1, "euUsdPerKg": 1.1, "naUsdPerKg": 1.1, "saUsdPerKg": 1.1}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:NA_SA', '1.1', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "NA_SA", "apaUsdPerKg": 1.1, "euUsdPerKg": 1.1, "naUsdPerKg": 1.1, "saUsdPerKg": 1.1}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:SA_NASeaAir', '1.1', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "SA_NASeaAir", "apaUsdPerKg": 1.1, "euUsdPerKg": 1.1, "naUsdPerKg": 1.1, "saUsdPerKg": 1.1}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:SA_SA', '1.1', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "SA_SA", "apaUsdPerKg": 1.1, "euUsdPerKg": 1.1, "naUsdPerKg": 1.1, "saUsdPerKg": 1.1}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:APA_EU', '6.6', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "APA_EU", "apaUsdPerKg": 6.6, "euUsdPerKg": 6.6, "naUsdPerKg": 6.6, "saUsdPerKg": 6.6}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:APA_NASeaAir', '6.6', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "APA_NASeaAir", "apaUsdPerKg": 6.6, "euUsdPerKg": 6.6, "naUsdPerKg": 6.6, "saUsdPerKg": 6.6}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:APA_SA', '6.6', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "APA_SA", "apaUsdPerKg": 6.6, "euUsdPerKg": 6.6, "naUsdPerKg": 6.6, "saUsdPerKg": 6.6}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:EU_APA', '6.6', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "EU_APA", "apaUsdPerKg": 6.6, "euUsdPerKg": 6.6, "naUsdPerKg": 6.6, "saUsdPerKg": 6.6}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:EU_NASeaAir', '6.6', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "EU_NASeaAir", "apaUsdPerKg": 6.6, "euUsdPerKg": 6.6, "naUsdPerKg": 6.6, "saUsdPerKg": 6.6}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:EU_SA', '6.6', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "EU_SA", "apaUsdPerKg": 6.6, "euUsdPerKg": 6.6, "naUsdPerKg": 6.6, "saUsdPerKg": 6.6}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:NA_APA', '6.6', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "NA_APA", "apaUsdPerKg": 6.6, "euUsdPerKg": 6.6, "naUsdPerKg": 6.6, "saUsdPerKg": 6.6}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:NA_EU', '6.6', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "NA_EU", "apaUsdPerKg": 6.6, "euUsdPerKg": 6.6, "naUsdPerKg": 6.6, "saUsdPerKg": 6.6}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:SA_APA', '6.6', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "SA_APA", "apaUsdPerKg": 6.6, "euUsdPerKg": 6.6, "naUsdPerKg": 6.6, "saUsdPerKg": 6.6}'::jsonb),
('lookup_table', 'USA', '2026-03', 'freightRates:SA_EU', '6.6', 'CostPerMass', 'Region-pair freight rate ($/kg) -- NOT auto-applied anywhere; migration 389 explicitly removed a previous FABRICATED flat $3.00/kg freight default as an anti-pattern violation. See project memory before ever wiring this into packaging_logistics_cost_records -- needs explicit user decision, never automatic.', '{"rateType": "SA_EU", "apaUsdPerKg": 6.6, "euUsdPerKg": 6.6, "naUsdPerKg": 6.6, "saUsdPerKg": 6.6}'::jsonb),
('lookup_table', 'USA', '2026-03', 'machiningProcessSetupTime:cncMachiningLarge', '60.0', 'Time', 'Generic process setup time (min) by large/small bucket -- this app''s cost-cnc-engine.ts already has more granular real per-machine-class setup times (BASE_SETUP_MIN); different taxonomy, not a gap. Grinding/wireEdm rows are progressive-die tooling fab, no consumer.', '{"process": "cncMachiningLarge", "setupTimeMin": 60.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'machiningProcessSetupTime:cncMachiningSmall', '10.0', 'Time', 'Generic process setup time (min) by large/small bucket -- this app''s cost-cnc-engine.ts already has more granular real per-machine-class setup times (BASE_SETUP_MIN); different taxonomy, not a gap. Grinding/wireEdm rows are progressive-die tooling fab, no consumer.', '{"process": "cncMachiningSmall", "setupTimeMin": 10.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'machiningProcessSetupTime:grinding', '5.0', 'Time', 'Generic process setup time (min) by large/small bucket -- this app''s cost-cnc-engine.ts already has more granular real per-machine-class setup times (BASE_SETUP_MIN); different taxonomy, not a gap. Grinding/wireEdm rows are progressive-die tooling fab, no consumer.', '{"process": "grinding", "setupTimeMin": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'machiningProcessSetupTime:wireEdm', '10.0', 'Time', 'Generic process setup time (min) by large/small bucket -- this app''s cost-cnc-engine.ts already has more granular real per-machine-class setup times (BASE_SETUP_MIN); different taxonomy, not a gap. Grinding/wireEdm rows are progressive-die tooling fab, no consumer.', '{"process": "wireEdm", "setupTimeMin": 10.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'materialTypeName:DP', 'DP', NULL, 'Material name -> raw material type classification (feeds drawForceFactor/numQualityLoops progressive-die tables) -- not this app''s own classifyMaterialFamily() axis (carbon_steel/stainless/aluminum for laser-speed factors); different purpose, no direct consumer', '{"materialName": "DP", "rawMaterialType": "DP"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'materialTypeName:Stainless- 304', 'high strength', NULL, 'Material name -> raw material type classification (feeds drawForceFactor/numQualityLoops progressive-die tables) -- not this app''s own classifyMaterialFamily() axis (carbon_steel/stainless/aluminum for laser-speed factors); different purpose, no direct consumer', '{"materialName": "Stainless- 304", "rawMaterialType": "high strength"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'materialTypeName:Stainless- 316', 'high strength', NULL, 'Material name -> raw material type classification (feeds drawForceFactor/numQualityLoops progressive-die tables) -- not this app''s own classifyMaterialFamily() axis (carbon_steel/stainless/aluminum for laser-speed factors); different purpose, no direct consumer', '{"materialName": "Stainless- 316", "rawMaterialType": "high strength"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'materialTypeName:Stainless- 316L', 'high strength', NULL, 'Material name -> raw material type classification (feeds drawForceFactor/numQualityLoops progressive-die tables) -- not this app''s own classifyMaterialFamily() axis (carbon_steel/stainless/aluminum for laser-speed factors); different purpose, no direct consumer', '{"materialName": "Stainless- 316L", "rawMaterialType": "high strength"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'materialTypeName:Steel- CR- 1010', 'mild steel', NULL, 'Material name -> raw material type classification (feeds drawForceFactor/numQualityLoops progressive-die tables) -- not this app''s own classifyMaterialFamily() axis (carbon_steel/stainless/aluminum for laser-speed factors); different purpose, no direct consumer', '{"materialName": "Steel- CR- 1010", "rawMaterialType": "mild steel"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'materialTypeName:Steel- CR- 1012', 'mild steel', NULL, 'Material name -> raw material type classification (feeds drawForceFactor/numQualityLoops progressive-die tables) -- not this app''s own classifyMaterialFamily() axis (carbon_steel/stainless/aluminum for laser-speed factors); different purpose, no direct consumer', '{"materialName": "Steel- CR- 1012", "rawMaterialType": "mild steel"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'materialTypeName:Steel- CR- 1020', 'mild steel', NULL, 'Material name -> raw material type classification (feeds drawForceFactor/numQualityLoops progressive-die tables) -- not this app''s own classifyMaterialFamily() axis (carbon_steel/stainless/aluminum for laser-speed factors); different purpose, no direct consumer', '{"materialName": "Steel- CR- 1020", "rawMaterialType": "mild steel"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'materialTypeName:Steel- HR- 1010', 'mild steel', NULL, 'Material name -> raw material type classification (feeds drawForceFactor/numQualityLoops progressive-die tables) -- not this app''s own classifyMaterialFamily() axis (carbon_steel/stainless/aluminum for laser-speed factors); different purpose, no direct consumer', '{"materialName": "Steel- HR- 1010", "rawMaterialType": "mild steel"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'materialTypeName:Steel- HR- 1012', 'mild steel', NULL, 'Material name -> raw material type classification (feeds drawForceFactor/numQualityLoops progressive-die tables) -- not this app''s own classifyMaterialFamily() axis (carbon_steel/stainless/aluminum for laser-speed factors); different purpose, no direct consumer', '{"materialName": "Steel- HR- 1012", "rawMaterialType": "mild steel"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'materialTypeName:Steel- HR- 1020', 'mild steel', NULL, 'Material name -> raw material type classification (feeds drawForceFactor/numQualityLoops progressive-die tables) -- not this app''s own classifyMaterialFamily() axis (carbon_steel/stainless/aluminum for laser-speed factors); different purpose, no direct consumer', '{"materialName": "Steel- HR- 1020", "rawMaterialType": "mild steel"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'numQualityLoops:0.7:DP', '5.0', NULL, 'Progressive-die try-out quality-loop count by thickness/material type -- this app has no progressive-die tooling try-out process', '{"rawMaterialThicknessMm": 0.7, "rawMaterialType": "DP", "numQualityLoops": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'numQualityLoops:0.7:high strength', '4.0', NULL, 'Progressive-die try-out quality-loop count by thickness/material type -- this app has no progressive-die tooling try-out process', '{"rawMaterialThicknessMm": 0.7, "rawMaterialType": "high strength", "numQualityLoops": 4.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'numQualityLoops:0.7:mild steel', '3.0', NULL, 'Progressive-die try-out quality-loop count by thickness/material type -- this app has no progressive-die tooling try-out process', '{"rawMaterialThicknessMm": 0.7, "rawMaterialType": "mild steel", "numQualityLoops": 3.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'numQualityLoops:4.0:DP', '4.0', NULL, 'Progressive-die try-out quality-loop count by thickness/material type -- this app has no progressive-die tooling try-out process', '{"rawMaterialThicknessMm": 4.0, "rawMaterialType": "DP", "numQualityLoops": 4.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'numQualityLoops:4.0:high strength', '3.0', NULL, 'Progressive-die try-out quality-loop count by thickness/material type -- this app has no progressive-die tooling try-out process', '{"rawMaterialThicknessMm": 4.0, "rawMaterialType": "high strength", "numQualityLoops": 3.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'numQualityLoops:4.0:mild steel', '2.0', NULL, 'Progressive-die try-out quality-loop count by thickness/material type -- this app has no progressive-die tooling try-out process', '{"rawMaterialThicknessMm": 4.0, "rawMaterialType": "mild steel", "numQualityLoops": 2.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'numQualityLoops:999.0:DP', '5.0', NULL, 'Progressive-die try-out quality-loop count by thickness/material type -- this app has no progressive-die tooling try-out process', '{"rawMaterialThicknessMm": 999.0, "rawMaterialType": "DP", "numQualityLoops": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'numQualityLoops:999.0:high strength', '4.0', NULL, 'Progressive-die try-out quality-loop count by thickness/material type -- this app has no progressive-die tooling try-out process', '{"rawMaterialThicknessMm": 999.0, "rawMaterialType": "high strength", "numQualityLoops": 4.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'numQualityLoops:999.0:mild steel', '3.0', NULL, 'Progressive-die try-out quality-loop count by thickness/material type -- this app has no progressive-die tooling try-out process', '{"rawMaterialThicknessMm": 999.0, "rawMaterialType": "mild steel", "numQualityLoops": 3.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'pressMaterialAdvanceRate:0.0', '60.0', 'Rate', 'Progressive Die press strokes-per-minute by part length -- source file itself filed under ''Progressive Die''; this app has no progressive-die process', '{"partLengthMm": 0.0, "strokesPerMinute": 60.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'pressMaterialAdvanceRate:50.8', '60.0', 'Rate', 'Progressive Die press strokes-per-minute by part length -- source file itself filed under ''Progressive Die''; this app has no progressive-die process', '{"partLengthMm": 50.8, "strokesPerMinute": 60.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'pressMaterialAdvanceRate:101.6', '30.0', 'Rate', 'Progressive Die press strokes-per-minute by part length -- source file itself filed under ''Progressive Die''; this app has no progressive-die process', '{"partLengthMm": 101.6, "strokesPerMinute": 30.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'pressMaterialAdvanceRate:152.4', '20.0', 'Rate', 'Progressive Die press strokes-per-minute by part length -- source file itself filed under ''Progressive Die''; this app has no progressive-die process', '{"partLengthMm": 152.4, "strokesPerMinute": 20.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'pressMaterialAdvanceRate:304.8', '10.0', 'Rate', 'Progressive Die press strokes-per-minute by part length -- source file itself filed under ''Progressive Die''; this app has no progressive-die process', '{"partLengthMm": 304.8, "strokesPerMinute": 10.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'pressMaterialAdvanceRate:999999999.0', '5.0', 'Rate', 'Progressive Die press strokes-per-minute by part length -- source file itself filed under ''Progressive Die''; this app has no progressive-die process', '{"partLengthMm": 999999999.0, "strokesPerMinute": 5.0}'::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;
