-- ============================================================================
-- Migration: Sheet Metal Lookup Tables -- Manufacturability Severity (staging)
-- Purpose: Lands the "manufacturabilitySeverity" export (53 rows) -- the
--          real severity (Critical/Major/Minor) and, for several rules,
--          quantified per-material/per-thickness thresholds behind the 70
--          named DFM advice rules staged earlier (migration 483). Into the
--          same lossless staging table earlier Lookup Tables migrations
--          created. See migration 479's header for the staging/promotion
--          architecture.
--
--          NOT auto-promoted into dfm-scoring.service.ts -- see project
--          memory project_manufacturing_intelligence_data_reconciliation.md
--          for the full cross-reference. Headline finding: this export has
--          a REAL, per-material, per-thickness-bracket minimum bend-radius
--          factor table (InsufficientBendRadius rows, 10 material types x
--          up to 3 thickness brackets) -- e.g. Steel: 0.8x at <=6mm,
--          1.2x at <=12mm, 1.5x at <=25mm. This app's live, consumer-facing
--          DFM engine (dfm-scoring.service.ts) uses a single flat 0.8x
--          threshold for every material at every thickness -- meaning it
--          under-flags crack risk for anything thicker than the thinnest
--          bracket, for every material except mild steel. This is a real,
--          quantified, actionable gap -- but changing dfm-scoring.service.ts
--          changes live risk flags shown to users, so it needs explicit
--          sign-off before any code change, never a silent promotion here.
-- Author: Principal Engineering Team
-- Date: 2026-08-19
-- Version: 1.0.0
-- ============================================================================

INSERT INTO sm_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('lookup_table', 'USA', '2026-03', 'BendInsideComplexHole:Boolean', 'TRUE', NULL, 'Flagged when a bend ends in a complex hole.', '{"ruleName": "BendInsideComplexHole", "thresholdName": "Bend Inside Complex Hole", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when a bend ends in a complex hole.", "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'BendIntersectsForm:Boolean', 'TRUE', NULL, 'Flagged when a bend intersects a form that is not of sub...', '{"ruleName": "BendIntersectsForm", "thresholdName": "Bend Intersects Form", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when a bend intersects a form that is not of sub...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'BlankOverlaps:Boolean', 'TRUE', NULL, 'Flagged when the flat pattern of the blank overlaps.', '{"ruleName": "BlankOverlaps", "thresholdName": "Blank Overlaps", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when the flat pattern of the blank overlaps.", "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'BlindHole:Boolean', 'TRUE', NULL, 'Flagged when a holemaking operation cannot manufact...', '{"ruleName": "BlindHole", "thresholdName": "Blind Hole", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when a holemaking operation cannot manufact...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'ExcessiveBendLength:Boolean', 'TRUE', NULL, 'Flagged if bend length is greater than the allowable maxi...', '{"ruleName": "ExcessiveBendLength", "thresholdName": "Max Bend Length", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged if bend length is greater than the allowable maxi...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'ExcessiveBendRadius:Boolean', 'TRUE', NULL, 'Flagged when the radius of a bend (that otherwise does ...', '{"ruleName": "ExcessiveBendRadius", "thresholdName": "Excessive Bend Radius", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": null, "major": "TRUE", "minor": null, "units": null, "notes": "Flagged when the radius of a bend (that otherwise does ...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'ExcessiveFlangeAngle:1000', '>', '180', 'Flagged when the distance between bends is less than th...', '{"ruleName": "ExcessiveFlangeAngle", "thresholdName": "Excessive Flange Angle", "processName": null, "materialType": null, "customField": "Maximum Return Bend Distance", "customValue": "1000", "ruleType": ">", "thresholdType": "Angle", "critical": null, "major": null, "minor": null, "units": "180", "notes": "Flagged when the distance between bends is less than th...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'FlangedHole:Boolean', 'TRUE', NULL, 'Flagged when hole flanging is not feasible.', '{"ruleName": "FlangedHole", "thresholdName": "Flanged Hole", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when hole flanging is not feasible.", "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendLength:Factor', '5', NULL, 'Flagged when the bend length is less than the stock thic...', '{"ruleName": "InsufficientBendLength", "thresholdName": "Insufficient Bend Length", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": null, "minor": "5", "units": null, "notes": "Flagged when the bend length is less than the stock thic...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendLength:Bend Brake', '10', 'mm', 'Flagged when the bend length is less than the maximum...', '{"ruleName": "InsufficientBendLength", "thresholdName": "Insufficient Bend Length", "processName": "Bend Brake", "materialType": null, "customField": null, "customValue": null, "ruleType": "<", "thresholdType": "Length", "critical": null, "major": null, "minor": "10", "units": "mm", "notes": "Flagged when the bend length is less than the maximum...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Aluminum:12', '1.5', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Aluminum", "customField": "Blank Thickness", "customValue": "12", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "1.5", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Aluminum:25', '2', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Aluminum", "customField": "Blank Thickness", "customValue": "25", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "2", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Aluminum:6', '1', NULL, 'Flagged when the bend radius is smaller than the recom...', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Aluminum", "customField": "Blank Thickness", "customValue": "6", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "1", "units": null, "notes": "Flagged when the bend radius is smaller than the recom...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Brass', '0.5', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Brass", "customField": null, "customValue": null, "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "0.5", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Copper', '0.5', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Copper", "customField": null, "customValue": null, "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "0.5", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Galvanized Steel', '3.5', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Galvanized Steel", "customField": null, "customValue": null, "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "3.5", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Heat Resistant Super Alloys:1.24', '1', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Heat Resistant Super Alloys", "customField": "Blank Thickness", "customValue": "1.24", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "1", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Heat Resistant Super Alloys:6.35', '2', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Heat Resistant Super Alloys", "customField": "Blank Thickness", "customValue": "6.35", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "2", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Low-Alloy Steel:12', '1.2', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Low-Alloy Steel", "customField": "Blank Thickness", "customValue": "12", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "1.2", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Low-Alloy Steel:25', '1.5', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Low-Alloy Steel", "customField": "Blank Thickness", "customValue": "25", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "1.5", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Low-Alloy Steel:6', '0.8', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Low-Alloy Steel", "customField": "Blank Thickness", "customValue": "6", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "0.8", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Stainless Steel:12', '2.5', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Stainless Steel", "customField": "Blank Thickness", "customValue": "12", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "2.5", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Stainless Steel:25', '3', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Stainless Steel", "customField": "Blank Thickness", "customValue": "25", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "3", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Stainless Steel:6', '2', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Stainless Steel", "customField": "Blank Thickness", "customValue": "6", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "2", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Steel:12', '1.2', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Steel", "customField": "Blank Thickness", "customValue": "12", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "1.2", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Steel:25', '1.5', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Steel", "customField": "Blank Thickness", "customValue": "25", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "1.5", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Steel:6', '0.8', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Steel", "customField": "Blank Thickness", "customValue": "6", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "0.8", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Titanium:12', '4.5', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Titanium", "customField": "Blank Thickness", "customValue": "12", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "4.5", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Unalloyed Steel:12', '1.2', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Unalloyed Steel", "customField": "Blank Thickness", "customValue": "12", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "1.2", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Unalloyed Steel:25', '1.5', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Unalloyed Steel", "customField": "Blank Thickness", "customValue": "25", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "1.5", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendRadius:Unalloyed Steel:6', '0.8', NULL, 'Rule type: <, threshold type: Factor', '{"ruleName": "InsufficientBendRadius", "thresholdName": "Min Bend Radius", "processName": null, "materialType": "Unalloyed Steel", "customField": "Blank Thickness", "customValue": "6", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": "0.01", "minor": "0.8", "units": null, "notes": null, "notesTruncatedInSource": false}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientBendToFormDistance:Factor', '3.5', NULL, 'Flagged when the distance between a straight bend and ...', '{"ruleName": "InsufficientBendToFormDistance", "thresholdName": "Insufficient Bend to Form Distance", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": null, "minor": "3.5", "units": null, "notes": "Flagged when the distance between a straight bend and ...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientFlangeGap:90', '8', NULL, 'Flagged when the gap between flanges in a return bend i...', '{"ruleName": "InsufficientFlangeGap", "thresholdName": "Insufficient Flange Gap", "processName": null, "materialType": null, "customField": "Return Bend Combined Angle", "customValue": "90", "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": null, "minor": "8", "units": null, "notes": "Flagged when the gap between flanges in a return bend i...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientHoleToBendDistance:Factor', '1.5', NULL, 'Flagged when the distance between a hole and a straight...', '{"ruleName": "InsufficientHoleToBendDistance", "thresholdName": "Insufficient Hole to Bend Distance", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": null, "minor": "1.5", "units": null, "notes": "Flagged when the distance between a hole and a straight...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientHoleToFormDistance:Factor', '1.5', NULL, 'Flagged when the distance between a hole and a form is ...', '{"ruleName": "InsufficientHoleToFormDistance", "thresholdName": "Insufficient Hole to Form Distance", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "<", "thresholdType": "Factor", "critical": null, "major": null, "minor": "1.5", "units": null, "notes": "Flagged when the distance between a hole and a form is ...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'InsufficientRollBendRadius:Boolean', 'Boolean', NULL, 'Flagged if bend radius is below the recommended mini...', '{"ruleName": "InsufficientRollBendRadius", "thresholdName": "Min Roll Bend Radius", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": null, "major": null, "minor": null, "units": null, "notes": "Flagged if bend radius is below the recommended mini...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'SmallInternalRadius:Boolean', 'TRUE', NULL, 'Flagged when internal radius is too small on a complex h...', '{"ruleName": "SmallInternalRadius", "thresholdName": "Small Internal Radius", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when internal radius is too small on a complex h...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceCircularity:Boolean', 'TRUE', NULL, 'Flagged when circularity tolerance exceeds the capability...', '{"ruleName": "TightToleranceCircularity", "thresholdName": "Tolerance - circularity", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when circularity tolerance exceeds the capability...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceConcentricity:Boolean', 'TRUE', NULL, 'Flagged when concentricity tolerance exceeds the capab...', '{"ruleName": "TightToleranceConcentricity", "thresholdName": "Tolerance - concentricity", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when concentricity tolerance exceeds the capab...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceCoordinateTolerance:Boolean', 'TRUE', NULL, 'Flagged when coordinate tolerance exceeds the capabilit...', '{"ruleName": "TightToleranceCoordinateTolerance", "thresholdName": "Tolerance - tolerance", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when coordinate tolerance exceeds the capabilit...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceCylindricity:Boolean', 'TRUE', NULL, 'Flagged when cylindricity tolerance exceeds the capability...', '{"ruleName": "TightToleranceCylindricity", "thresholdName": "Tolerance - cylindricity", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when cylindricity tolerance exceeds the capability...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceDiamTolerance:Boolean', 'TRUE', NULL, 'Flagged when diametric tolerance exceeds the capability...', '{"ruleName": "TightToleranceDiamTolerance", "thresholdName": "Tolerance - diamTolerance", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when diametric tolerance exceeds the capability...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceFlatness:Boolean', 'TRUE', NULL, 'Flagged when flatness tolerance exceeds the capability o...', '{"ruleName": "TightToleranceFlatness", "thresholdName": "Tolerance - flatness", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when flatness tolerance exceeds the capability o...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceParallelism:Boolean', 'TRUE', NULL, 'Flagged when parallelism tolerance exceeds the capabilit...', '{"ruleName": "TightToleranceParallelism", "thresholdName": "Tolerance - parallelism", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when parallelism tolerance exceeds the capabilit...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightTolerancePerpendicularity:Boolean', 'TRUE', NULL, 'Flagged when perpendicularity tolerance exceeds the ca...', '{"ruleName": "TightTolerancePerpendicularity", "thresholdName": "Tolerance - perpendicularity", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when perpendicularity tolerance exceeds the ca...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightTolerancePositionTolerance:Boolean', 'TRUE', NULL, 'Flagged when position tolerance exceeds the capability ...', '{"ruleName": "TightTolerancePositionTolerance", "thresholdName": "Tolerance - positionTolerance", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when position tolerance exceeds the capability ...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceProfileOfSurface:Boolean', 'TRUE', NULL, 'Flagged when profile of surface tolerance exceeds the ca...', '{"ruleName": "TightToleranceProfileOfSurface", "thresholdName": "Tolerance - profileOfSurface", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when profile of surface tolerance exceeds the ca...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceRoughnessRa:Boolean', 'TRUE', NULL, 'Flagged when roughness Ra tolerance exceeds the capab...', '{"ruleName": "TightToleranceRoughnessRa", "thresholdName": "Tolerance - roughness", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when roughness Ra tolerance exceeds the capab...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceRoughnessRz:Boolean', 'TRUE', NULL, 'Flagged when roughness Rz tolerance exceeds the capab...', '{"ruleName": "TightToleranceRoughnessRz", "thresholdName": "Tolerance - roughnessRz", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when roughness Rz tolerance exceeds the capab...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceRunout:Boolean', 'TRUE', NULL, 'Flagged when runout tolerance exceeds the capability of...', '{"ruleName": "TightToleranceRunout", "thresholdName": "Tolerance - runout", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when runout tolerance exceeds the capability of...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceStraightness:Boolean', 'TRUE', NULL, 'Flagged when straightness tolerance exceeds the capabil...', '{"ruleName": "TightToleranceStraightness", "thresholdName": "Tolerance - straightness", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when straightness tolerance exceeds the capabil...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceSymmetry:Boolean', 'TRUE', NULL, 'Flagged when symmetry tolerance exceeds the capabilit...', '{"ruleName": "TightToleranceSymmetry", "thresholdName": "Tolerance - symmetry", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when symmetry tolerance exceeds the capabilit...", "notesTruncatedInSource": true}'::jsonb),
('lookup_table', 'USA', '2026-03', 'TightToleranceTotalRunout:Boolean', 'TRUE', NULL, 'Flagged when total runout tolerance exceeds the capabilit...', '{"ruleName": "TightToleranceTotalRunout", "thresholdName": "Tolerance - totalRunout", "processName": null, "materialType": null, "customField": null, "customValue": null, "ruleType": "Boolean", "thresholdType": "Boolean", "critical": "TRUE", "major": null, "minor": null, "units": null, "notes": "Flagged when total runout tolerance exceeds the capabilit...", "notesTruncatedInSource": true}'::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;
