-- ============================================================================
-- Migration: Sheet Metal Lookup Tables -- combined export batch 2 (staging)
-- Purpose: Lands 8 more lookup tables (tblToolLife already staged separately
--          as migration 513, skipped here) into the same lossless staging
--          table earlier migrations created. See migration 479's header for
--          the staging/promotion architecture. Source name sanitized per
--          the standing rule against naming the licensed source.
--
--          Per-table consumer check (grepped the live cost-engine code
--          before staging, per this reconciliation's standing practice):
--
--          - tblRouterUtilities (8 rows, cutting speed/feed by material +
--            tool diameter): "2 Axis Router" has NO cost engine in this app
--            at all (confirmed repeatedly this session) -- no consumer.
--          - tblWaterjetAbrasiveNozzle (3 rows, nozzle cost + life in hours
--            by grade): this app's waterjet costing (waterjet-engine.ts)
--            amortizes ABRASIVE MATERIAL cost (consumable_prices table,
--            migration 362) but has NO nozzle-wear cost term at all -- a
--            real, distinct, currently-missing cost line item. NOT added
--            here -- adding a new cost term to a live formula is a real
--            product decision (changes every existing waterjet quote's
--            cost), not a data fix. Flagged for a decision, not built.
--          - tblWaterjetMachinabilityFactor (21 rows, material-cut-code-
--            family -> speed multiplier): this app's real
--            sm_lookup_waterjet_cut table (migration 398) already varies
--            cutting speed by material+thickness directly (not via a
--            separate multiplier layer) -- this export's material-cut-code
--            axis has no established mapping to this app's own material
--            classification, so it can't be safely cross-applied. Staged
--            for reference only.
--          - tblWaterjetCutGasRate (3 rows, Oxygen/Air/Nitrogen cost +
--            orifice life): despite the "WaterjetCut" file path, assist gas
--            is a LASER cutting concept (waterjet uses water+abrasive, not
--            process gas) -- likely the source tool's own folder
--            organization, not evidence this app's waterjet process needs a
--            gas cost term. No consumer either way.
--          - toolingHeatTreatCost / toolingHeatTreatCostMaterial (6+8 rows)
--            and tblToolLifeImprovementFactor (10 rows, coating type ->
--            tool life multiplier): all describe STAMPING TOOL fabrication
--            costs (build/harden/coat a die) -- this app does not build or
--            cost tooling at all (it costs the PART on an assumed-available
--            machine), so there is no live concept these could feed. No
--            consumer.
--          - validationDisplayControls (11 rows, panel name -> show/hide):
--            this is the SOURCE TOOL's own UI configuration (which of ITS
--            OWN panels are visible), not manufacturing data at all --
--            staged only for completeness/losslessness, explicitly not
--            manufacturing reference data.
-- Author: Principal Engineering Team
-- Date: 2026-08-20
-- Version: 1.0.0
-- ============================================================================

INSERT INTO sm_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('lookup_table', 'USA', '2026-03', 'tblRouterUtilities:350.52:0.0254:Aluminum:3.0', '350.52', NULL, 'From tblLookupTables export, table ''tblRouterUtilities'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblRouterUtilities", "file_path": "lookupTables/Component/tblRouterUtilities.csv", "Cutting Speed (m/min)": 350.52, "Feed Per Tooth (mm)": 0.0254, "Material Family": "Aluminum", "Tool Diameter (mm)": 3.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblRouterUtilities:350.52:0.0254:Copper:3.0', '350.52', NULL, 'From tblLookupTables export, table ''tblRouterUtilities'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblRouterUtilities", "file_path": "lookupTables/Component/tblRouterUtilities.csv", "Cutting Speed (m/min)": 350.52, "Feed Per Tooth (mm)": 0.0254, "Material Family": "Copper", "Tool Diameter (mm)": 3.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblRouterUtilities:350.52:0.0508:Aluminum:6.0', '350.52', NULL, 'From tblLookupTables export, table ''tblRouterUtilities'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblRouterUtilities", "file_path": "lookupTables/Component/tblRouterUtilities.csv", "Cutting Speed (m/min)": 350.52, "Feed Per Tooth (mm)": 0.0508, "Material Family": "Aluminum", "Tool Diameter (mm)": 6.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblRouterUtilities:350.52:0.0508:Copper:6.0', '350.52', NULL, 'From tblLookupTables export, table ''tblRouterUtilities'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblRouterUtilities", "file_path": "lookupTables/Component/tblRouterUtilities.csv", "Cutting Speed (m/min)": 350.52, "Feed Per Tooth (mm)": 0.0508, "Material Family": "Copper", "Tool Diameter (mm)": 6.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblRouterUtilities:350.52:0.0635:Copper:10.0', '350.52', NULL, 'From tblLookupTables export, table ''tblRouterUtilities'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblRouterUtilities", "file_path": "lookupTables/Component/tblRouterUtilities.csv", "Cutting Speed (m/min)": 350.52, "Feed Per Tooth (mm)": 0.0635, "Material Family": "Copper", "Tool Diameter (mm)": 10.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblRouterUtilities:350.52:0.0762:Aluminum:10.0', '350.52', NULL, 'From tblLookupTables export, table ''tblRouterUtilities'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblRouterUtilities", "file_path": "lookupTables/Component/tblRouterUtilities.csv", "Cutting Speed (m/min)": 350.52, "Feed Per Tooth (mm)": 0.0762, "Material Family": "Aluminum", "Tool Diameter (mm)": 10.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblRouterUtilities:350.52:0.0762:Copper:12.0', '350.52', NULL, 'From tblLookupTables export, table ''tblRouterUtilities'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblRouterUtilities", "file_path": "lookupTables/Component/tblRouterUtilities.csv", "Cutting Speed (m/min)": 350.52, "Feed Per Tooth (mm)": 0.0762, "Material Family": "Copper", "Tool Diameter (mm)": 12.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblRouterUtilities:350.52:0.1016:Aluminum:12.0', '350.52', NULL, 'From tblLookupTables export, table ''tblRouterUtilities'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblRouterUtilities", "file_path": "lookupTables/Component/tblRouterUtilities.csv", "Cutting Speed (m/min)": 350.52, "Feed Per Tooth (mm)": 0.1016, "Material Family": "Aluminum", "Tool Diameter (mm)": 12.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetAbrasiveNozzle:Low-Cost Composite Carbide:50.0:45.0', '50.0', NULL, 'From tblLookupTables export, table ''tblWaterjetAbrasiveNozzle'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetAbrasiveNozzle", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetAbrasiveNozzle.csv", "Nozzle Type": "Low-Cost Composite Carbide", "Nozzle Cost (USD)": 50.0, "Nozzle Life (hr)": 45.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetAbrasiveNozzle:Mid-Life Composite Carbide:100.0:85.0', '100.0', NULL, 'From tblLookupTables export, table ''tblWaterjetAbrasiveNozzle'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetAbrasiveNozzle", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetAbrasiveNozzle.csv", "Nozzle Type": "Mid-Life Composite Carbide", "Nozzle Cost (USD)": 100.0, "Nozzle Life (hr)": 85.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetAbrasiveNozzle:Premium Composite Carbide:150.0:125.0', '150.0', NULL, 'From tblLookupTables export, table ''tblWaterjetAbrasiveNozzle'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetAbrasiveNozzle", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetAbrasiveNozzle.csv", "Nozzle Type": "Premium Composite Carbide", "Nozzle Cost (USD)": 150.0, "Nozzle Life (hr)": 125.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:1:81.2', '1', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 1, "Machinability Factor": 81.2}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:10:54.08', '10', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 10, "Machinability Factor": 54.08}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:15:82.5', '15', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 15, "Machinability Factor": 82.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:2:81.3', '2', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 2, "Machinability Factor": 81.3}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:20:82.6', '20', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 20, "Machinability Factor": 82.6}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:23:108.3', '23', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 23, "Machinability Factor": 108.3}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:3:67.6', '3', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 3, "Machinability Factor": 67.6}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:30:219.3', '30', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 30, "Machinability Factor": 219.3}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:33:102.8', '33', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 33, "Machinability Factor": 102.8}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:34:25.06', '34', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 34, "Machinability Factor": 25.06}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:4:54.08', '4', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 4, "Machinability Factor": 54.08}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:41:72.27', '41', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 41, "Machinability Factor": 72.27}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:42:72.27', '42', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 42, "Machinability Factor": 72.27}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:5:82.5', '5', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 5, "Machinability Factor": 82.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:51:387.7', '51', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 51, "Machinability Factor": 387.7}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:52:387.7', '52', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 52, "Machinability Factor": 387.7}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:6:81.3', '6', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 6, "Machinability Factor": 81.3}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:60:300.0', '60', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 60, "Machinability Factor": 300.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:7:72.0', '7', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 7, "Machinability Factor": 72.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:8:72.0', '8', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 8, "Machinability Factor": 72.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetMachinabilityFactor:9:72.0', '9', NULL, 'From tblLookupTables export, table ''tblWaterjetMachinabilityFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetMachinabilityFactor", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetMachinabilityFactor.csv", "Material Cut Code Family": 9, "Machinability Factor": 72.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetCutGasRate:Oxygen:100.0:50.0', '100.0', NULL, 'From tblLookupTables export, table ''tblWaterjetCutGasRate'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetCutGasRate", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetCutGasRate.csv", "Gas Type": "Oxygen", "Cost (USD/kg)": 100.0, "Orifice Life (hr)": 50.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetCutGasRate:Air:22.5:50.0', '22.5', NULL, 'From tblLookupTables export, table ''tblWaterjetCutGasRate'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetCutGasRate", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetCutGasRate.csv", "Gas Type": "Air", "Cost (USD/kg)": 22.5, "Orifice Life (hr)": 50.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblWaterjetCutGasRate:Nitrogen:20.0:50.0', '20.0', NULL, 'From tblLookupTables export, table ''tblWaterjetCutGasRate'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblWaterjetCutGasRate", "file_path": "lookupTables/Component/WaterjetCut/tblWaterjetCutGasRate.csv", "Gas Type": "Nitrogen", "Cost (USD/kg)": 20.0, "Orifice Life (hr)": 50.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCost:0.05:stressRelieve:1020', '0.05', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCost'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCost", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Heat Treat Cost (USD/kg)": 0.05, "Heat Treat Type": "stressRelieve", "Tool Material": "1020"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCost:0.23:harden:O1', '0.23', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCost'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCost", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Heat Treat Cost (USD/kg)": 0.23, "Heat Treat Type": "harden", "Tool Material": "O1"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCost:0.23:harden:6150', '0.23', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCost'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCost", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Heat Treat Cost (USD/kg)": 0.23, "Heat Treat Type": "harden", "Tool Material": "6150"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCost:0.23:harden:A2', '0.23', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCost'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCost", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Heat Treat Cost (USD/kg)": 0.23, "Heat Treat Type": "harden", "Tool Material": "A2"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCost:0.23:harden:D2', '0.23', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCost'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCost", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Heat Treat Cost (USD/kg)": 0.23, "Heat Treat Type": "harden", "Tool Material": "D2"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCost:0.23:harden:S7', '0.23', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCost'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCost", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Heat Treat Cost (USD/kg)": 0.23, "Heat Treat Type": "harden", "Tool Material": "S7"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCostMaterial:O1:1.7', '1.7', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCostMaterial'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCostMaterial", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Material": "O1", "Cost (USD/kg)": 1.7}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCostMaterial:1010:1.07', '1.07', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCostMaterial'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCostMaterial", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Material": "1010", "Cost (USD/kg)": 1.07}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCostMaterial:1020:1.0', '1.0', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCostMaterial'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCostMaterial", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Material": "1020", "Cost (USD/kg)": 1.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCostMaterial:4140:1.09', '1.09', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCostMaterial'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCostMaterial", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Material": "4140", "Cost (USD/kg)": 1.09}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCostMaterial:6150:1.16', '1.16', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCostMaterial'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCostMaterial", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Material": "6150", "Cost (USD/kg)": 1.16}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCostMaterial:A2:1.01', '1.01', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCostMaterial'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCostMaterial", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Material": "A2", "Cost (USD/kg)": 1.01}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCostMaterial:D2:2.27', '2.27', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCostMaterial'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCostMaterial", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Material": "D2", "Cost (USD/kg)": 2.27}'::jsonb),
('lookup_table', 'USA', '2026-03', 'toolingHeatTreatCostMaterial:S7:2.04', '2.04', NULL, 'From tblLookupTables export, table ''toolingHeatTreatCostMaterial'' -- see migration 514 header for per-table consumer-check notes', '{"table": "toolingHeatTreatCostMaterial", "file_path": "lookupTables/Component/toolingHeatTreatCost.csv", "Material": "S7", "Cost (USD/kg)": 2.04}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblToolLifeImprovementFactor:1.0:None:1.0', '1.0', NULL, 'From tblLookupTables export, table ''tblToolLifeImprovementFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblToolLifeImprovementFactor", "file_path": "lookupTables/Component/tblToolLifeImprovementFactor.csv", "Coating Cost Factor (USD/kg)": 1.0, "Coating Type": "None", "Tool Life Improvement Factor": 1.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblToolLifeImprovementFactor:1.9:Tribo-coating:1.4', '1.9', NULL, 'From tblLookupTables export, table ''tblToolLifeImprovementFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblToolLifeImprovementFactor", "file_path": "lookupTables/Component/tblToolLifeImprovementFactor.csv", "Coating Cost Factor (USD/kg)": 1.9, "Coating Type": "Tribo-coating", "Tool Life Improvement Factor": 1.4}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblToolLifeImprovementFactor:2.8:Electroless Nickel:1.2', '2.8', NULL, 'From tblLookupTables export, table ''tblToolLifeImprovementFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblToolLifeImprovementFactor", "file_path": "lookupTables/Component/tblToolLifeImprovementFactor.csv", "Coating Cost Factor (USD/kg)": 2.8, "Coating Type": "Electroless Nickel", "Tool Life Improvement Factor": 1.2}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblToolLifeImprovementFactor:3.5:Electroless Teflon:1.5', '3.5', NULL, 'From tblLookupTables export, table ''tblToolLifeImprovementFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblToolLifeImprovementFactor", "file_path": "lookupTables/Component/tblToolLifeImprovementFactor.csv", "Coating Cost Factor (USD/kg)": 3.5, "Coating Type": "Electroless Teflon", "Tool Life Improvement Factor": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblToolLifeImprovementFactor:4.1:Nitrided Steel:1.1', '4.1', NULL, 'From tblLookupTables export, table ''tblToolLifeImprovementFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblToolLifeImprovementFactor", "file_path": "lookupTables/Component/tblToolLifeImprovementFactor.csv", "Coating Cost Factor (USD/kg)": 4.1, "Coating Type": "Nitrided Steel", "Tool Life Improvement Factor": 1.1}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblToolLifeImprovementFactor:4.4:Electroplated Chromium:1.3', '4.4', NULL, 'From tblLookupTables export, table ''tblToolLifeImprovementFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblToolLifeImprovementFactor", "file_path": "lookupTables/Component/tblToolLifeImprovementFactor.csv", "Coating Cost Factor (USD/kg)": 4.4, "Coating Type": "Electroplated Chromium", "Tool Life Improvement Factor": 1.3}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblToolLifeImprovementFactor:6.9:Plasma Sprayed:1.4', '6.9', NULL, 'From tblLookupTables export, table ''tblToolLifeImprovementFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblToolLifeImprovementFactor", "file_path": "lookupTables/Component/tblToolLifeImprovementFactor.csv", "Coating Cost Factor (USD/kg)": 6.9, "Coating Type": "Plasma Sprayed", "Tool Life Improvement Factor": 1.4}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblToolLifeImprovementFactor:10.2:PVD TiN:1.6', '10.2', NULL, 'From tblLookupTables export, table ''tblToolLifeImprovementFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblToolLifeImprovementFactor", "file_path": "lookupTables/Component/tblToolLifeImprovementFactor.csv", "Coating Cost Factor (USD/kg)": 10.2, "Coating Type": "PVD TiN", "Tool Life Improvement Factor": 1.6}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblToolLifeImprovementFactor:19.1:CVD TiC:1.9', '19.1', NULL, 'From tblLookupTables export, table ''tblToolLifeImprovementFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblToolLifeImprovementFactor", "file_path": "lookupTables/Component/tblToolLifeImprovementFactor.csv", "Coating Cost Factor (USD/kg)": 19.1, "Coating Type": "CVD TiC", "Tool Life Improvement Factor": 1.9}'::jsonb),
('lookup_table', 'USA', '2026-03', 'tblToolLifeImprovementFactor:25.0:Duplex/Variants:1.4', '25.0', NULL, 'From tblLookupTables export, table ''tblToolLifeImprovementFactor'' -- see migration 514 header for per-table consumer-check notes', '{"table": "tblToolLifeImprovementFactor", "file_path": "lookupTables/Component/tblToolLifeImprovementFactor.csv", "Coating Cost Factor (USD/kg)": 25.0, "Coating Type": "Duplex/Variants", "Tool Life Improvement Factor": 1.4}'::jsonb),
('lookup_table', 'USA', '2026-03', 'validationDisplayControls:Blank Size:yes', 'Blank Size', NULL, 'From tblLookupTables export, table ''validationDisplayControls'' -- see migration 514 header for per-table consumer-check notes', '{"table": "validationDisplayControls", "file_path": "lookupTables/Component/validationDisplayControls.csv", "Panel Name": "Blank Size", "Display": "yes"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'validationDisplayControls:Build Direction:no', 'Build Direction', NULL, 'From tblLookupTables export, table ''validationDisplayControls'' -- see migration 514 header for per-table consumer-check notes', '{"table": "validationDisplayControls", "file_path": "lookupTables/Component/validationDisplayControls.csv", "Panel Name": "Build Direction", "Display": "no"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'validationDisplayControls:Draw Direction:no', 'Draw Direction', NULL, 'From tblLookupTables export, table ''validationDisplayControls'' -- see migration 514 header for per-table consumer-check notes', '{"table": "validationDisplayControls", "file_path": "lookupTables/Component/validationDisplayControls.csv", "Panel Name": "Draw Direction", "Display": "no"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'validationDisplayControls:Machining:yes', 'Machining', NULL, 'From tblLookupTables export, table ''validationDisplayControls'' -- see migration 514 header for per-table consumer-check notes', '{"table": "validationDisplayControls", "file_path": "lookupTables/Component/validationDisplayControls.csv", "Panel Name": "Machining", "Display": "yes"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'validationDisplayControls:Main Surface:yes', 'Main Surface', NULL, 'From tblLookupTables export, table ''validationDisplayControls'' -- see migration 514 header for per-table consumer-check notes', '{"table": "validationDisplayControls", "file_path": "lookupTables/Component/validationDisplayControls.csv", "Panel Name": "Main Surface", "Display": "yes"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'validationDisplayControls:No Cost Feature:no', 'No Cost Feature', NULL, 'From tblLookupTables export, table ''validationDisplayControls'' -- see migration 514 header for per-table consumer-check notes', '{"table": "validationDisplayControls", "file_path": "lookupTables/Component/validationDisplayControls.csv", "Panel Name": "No Cost Feature", "Display": "no"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'validationDisplayControls:Ram Direction:no', 'Ram Direction', NULL, 'From tblLookupTables export, table ''validationDisplayControls'' -- see migration 514 header for per-table consumer-check notes', '{"table": "validationDisplayControls", "file_path": "lookupTables/Component/validationDisplayControls.csv", "Panel Name": "Ram Direction", "Display": "no"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'validationDisplayControls:Routing:yes', 'Routing', NULL, 'From tblLookupTables export, table ''validationDisplayControls'' -- see migration 514 header for per-table consumer-check notes', '{"table": "validationDisplayControls", "file_path": "lookupTables/Component/validationDisplayControls.csv", "Panel Name": "Routing", "Display": "yes"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'validationDisplayControls:Stock Form:no', 'Stock Form', NULL, 'From tblLookupTables export, table ''validationDisplayControls'' -- see migration 514 header for per-table consumer-check notes', '{"table": "validationDisplayControls", "file_path": "lookupTables/Component/validationDisplayControls.csv", "Panel Name": "Stock Form", "Display": "no"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'validationDisplayControls:Tolerances:yes', 'Tolerances', NULL, 'From tblLookupTables export, table ''validationDisplayControls'' -- see migration 514 header for per-table consumer-check notes', '{"table": "validationDisplayControls", "file_path": "lookupTables/Component/validationDisplayControls.csv", "Panel Name": "Tolerances", "Display": "yes"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'validationDisplayControls:Uncosted GCDs:yes', 'Uncosted GCDs', NULL, 'From tblLookupTables export, table ''validationDisplayControls'' -- see migration 514 header for per-table consumer-check notes', '{"table": "validationDisplayControls", "file_path": "lookupTables/Component/validationDisplayControls.csv", "Panel Name": "Uncosted GCDs", "Display": "yes"}'::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;
