-- ============================================================================
-- Migration: Sheet Metal Rules -- handling allowance, bend radius limit,
--            blank/hole guidance (staging)
-- Purpose: Lands the reconciliation export's handling-allowance/bend-radius/
--          blank-and-hole-guidance rules into the same lossless staging
--          table earlier migrations created. See migration 479's header for
--          the staging/promotion architecture. Source name sanitized per
--          the standing rule against naming the licensed source.
--
--          Real corroboration found (no code change needed -- these CONFIRM
--          values this app already uses, sourced independently earlier this
--          reconciliation):
--            - hole_guidance.common.holeToBend = 1.5 == this app's own
--              HOLE_TO_BEND_MIN_FACTOR (dfm-scoring.service.ts).
--            - hole_guidance.common.holeToHole = 2.0 == this app's own
--              PUNCH_INTERFERENCE check (nearest_hole_distance_mm < 2 x
--              diameter) in scoreSheetMetalHole().
--
--          Real gap found, NOT built (a new capability, not a data fix):
--          handling_allowance has 5 process-specific USD-by-weight-bracket
--          tables (Generic Press, Laser Punch, Plasma Punch, Std Press,
--          Turret Press handling) -- all five are IDENTICAL curves
--          (0kg->$0 ... 27kg->$9 ... 50kg->$25 ... above->$46). Turret Press
--          is a REAL, live-costed process in this app (Turret Punching/Hole
--          Punching/Nibbling); grepped for any "handling cost" concept in
--          this app's process costing and found none -- turret-punch (and
--          every press-family process) costing has NO material-handling
--          surcharge line item today. Adding one changes every existing
--          quote's cost for these processes -- a real product decision,
--          flagged for the user to decide on, not silently added.
--
--          dtc_bend_radius_limits (1 row, "Any" material, 0.5x multiplier)
--          is a generic catch-all fallback, coarser than this app's own
--          already-sourced per-material BEND_RADIUS_MIN_FACTOR table --
--          does NOT supersede it, staged for reference only.
--
--          blank_guidance (7 rows, minEdgeRadius/minUtilization by
--          operation) has no known consumer -- this app's blank/nesting
--          engine (sheet-metal-nesting.engine.ts) does not currently check
--          either metric.
-- Author: Principal Engineering Team
-- Date: 2026-08-20
-- Version: 1.0.0
-- ============================================================================

INSERT INTO sm_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smGenericPressHandling:0.0', '0.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smGenericPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 0.0, "weight_kg": 0.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smGenericPressHandling:1.0', '2.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smGenericPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 2.0, "weight_kg": 1.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smGenericPressHandling:5.0', '2.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smGenericPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 2.0, "weight_kg": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smGenericPressHandling:10.0', '4.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smGenericPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 4.0, "weight_kg": 10.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smGenericPressHandling:27.0', '9.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smGenericPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 9.0, "weight_kg": 27.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smGenericPressHandling:50.0', '25.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smGenericPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 25.0, "weight_kg": 50.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smGenericPressHandling:999999999.0', '46.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smGenericPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 46.0, "weight_kg": 999999999.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smLaserPunchHandling:0.0', '0.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smLaserPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 0.0, "weight_kg": 0.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smLaserPunchHandling:1.0', '2.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smLaserPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 2.0, "weight_kg": 1.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smLaserPunchHandling:5.0', '2.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smLaserPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 2.0, "weight_kg": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smLaserPunchHandling:10.0', '4.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smLaserPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 4.0, "weight_kg": 10.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smLaserPunchHandling:27.0', '9.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smLaserPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 9.0, "weight_kg": 27.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smLaserPunchHandling:50.0', '25.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smLaserPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 25.0, "weight_kg": 50.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smLaserPunchHandling:999999999.0', '46.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smLaserPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 46.0, "weight_kg": 999999999.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smPlasmaPunchHandling:0.0', '0.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smPlasmaPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 0.0, "weight_kg": 0.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smPlasmaPunchHandling:1.0', '2.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smPlasmaPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 2.0, "weight_kg": 1.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smPlasmaPunchHandling:5.0', '2.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smPlasmaPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 2.0, "weight_kg": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smPlasmaPunchHandling:10.0', '4.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smPlasmaPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 4.0, "weight_kg": 10.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smPlasmaPunchHandling:27.0', '9.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smPlasmaPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 9.0, "weight_kg": 27.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smPlasmaPunchHandling:50.0', '25.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smPlasmaPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 25.0, "weight_kg": 50.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smPlasmaPunchHandling:999999999.0', '46.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smPlasmaPunchHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 46.0, "weight_kg": 999999999.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smStdPressHandling:0.0', '0.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smStdPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 0.0, "weight_kg": 0.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smStdPressHandling:1.0', '2.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smStdPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 2.0, "weight_kg": 1.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smStdPressHandling:5.0', '2.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smStdPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 2.0, "weight_kg": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smStdPressHandling:10.0', '4.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smStdPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 4.0, "weight_kg": 10.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smStdPressHandling:27.0', '9.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smStdPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 9.0, "weight_kg": 27.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smStdPressHandling:50.0', '25.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smStdPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 25.0, "weight_kg": 50.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smStdPressHandling:999999999.0', '46.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smStdPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 46.0, "weight_kg": 999999999.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smTurretPressHandling:0.0', '0.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smTurretPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 0.0, "weight_kg": 0.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smTurretPressHandling:0.0', '2.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smTurretPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 2.0, "weight_kg": 0.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smTurretPressHandling:5.0', '2.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smTurretPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 2.0, "weight_kg": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smTurretPressHandling:10.0', '4.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smTurretPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 4.0, "weight_kg": 10.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smTurretPressHandling:27.0', '9.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smTurretPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 9.0, "weight_kg": 27.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smTurretPressHandling:50.0', '25.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smTurretPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 25.0, "weight_kg": 50.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'handlingAllowance:smTurretPressHandling:999999999.0', '46.0', 'Currency', 'Material handling cost (USD) by part weight bracket for smTurretPressHandling -- no handling-cost concept exists in this app''s process costing today (grepped for it)', '{"allowance_usd": 46.0, "weight_kg": 999999999.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'dtcBendRadiusLimit:Any', '0.5', 'Factor', 'Generic (material-agnostic) fallback bend-radius-to-thickness multiplier (0.5x) for thickness <=25.4mm -- this app already has a finer-grained, independently-sourced per-material bend radius table (BEND_RADIUS_MIN_FACTOR in default-rates.ts, e.g. steel=0.8-1.5x by thickness bracket) that this generic catch-all does NOT supersede -- staged for reference only, not applied', '{"material_composition": "Any", "material_type": "Any", "max_thickness_mm": 25.4, "multiplier": 0.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'blankGuidance:Other:minEdgeRadius', '0.5', 'factor', 'Blank-layout guidance (minEdgeRadius) for Other -- no known consumer in this app yet', '{"operation": "Other", "metric": "minEdgeRadius", "value": 0.5, "unit": "factor"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'blankGuidance:Other:minUtilization', '0.75', 'decimal', 'Blank-layout guidance (minUtilization) for Other -- no known consumer in this app yet', '{"operation": "Other", "metric": "minUtilization", "value": 0.75, "unit": "decimal"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'blankGuidance:Progressive Die:minEdgeRadius', '0.5', 'factor', 'Blank-layout guidance (minEdgeRadius) for Progressive Die -- no known consumer in this app yet', '{"operation": "Progressive Die", "metric": "minEdgeRadius", "value": 0.5, "unit": "factor"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'blankGuidance:Shear Press:minEdgeRadius', '0.5', 'factor', 'Blank-layout guidance (minEdgeRadius) for Shear Press -- no known consumer in this app yet', '{"operation": "Shear Press", "metric": "minEdgeRadius", "value": 0.5, "unit": "factor"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'blankGuidance:Stage Tooling:minEdgeRadius', '0.5', 'factor', 'Blank-layout guidance (minEdgeRadius) for Stage Tooling -- no known consumer in this app yet', '{"operation": "Stage Tooling", "metric": "minEdgeRadius", "value": 0.5, "unit": "factor"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'blankGuidance:Tandem Die:minEdgeRadius', '0.5', 'factor', 'Blank-layout guidance (minEdgeRadius) for Tandem Die -- no known consumer in this app yet', '{"operation": "Tandem Die", "metric": "minEdgeRadius", "value": 0.5, "unit": "factor"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'blankGuidance:Turret Press:minEdgeRadius', '0.5', 'factor', 'Blank-layout guidance (minEdgeRadius) for Turret Press -- no known consumer in this app yet', '{"operation": "Turret Press", "metric": "minEdgeRadius", "value": 0.5, "unit": "factor"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:common:holeToBend', '1.5', NULL, 'Hole-spacing guidance (holeToBend) for common -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "common", "metric": "holeToBend", "value": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:common:holeToBlank', '1.0', NULL, 'Hole-spacing guidance (holeToBlank) for common -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "common", "metric": "holeToBlank", "value": 1.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:common:holeToHole', '2.0', NULL, 'Hole-spacing guidance (holeToHole) for common -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "common", "metric": "holeToHole", "value": 2.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:generic_press_piercing:holeToBend', '1.5', NULL, 'Hole-spacing guidance (holeToBend) for generic_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "generic_press_piercing", "metric": "holeToBend", "value": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:generic_press_piercing:largerHoleToBlank', '2.0', NULL, 'Hole-spacing guidance (largerHoleToBlank) for generic_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "generic_press_piercing", "metric": "largerHoleToBlank", "value": 2.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:generic_press_piercing:largerHoleToBlankThreshold', '5.0', NULL, 'Hole-spacing guidance (largerHoleToBlankThreshold) for generic_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "generic_press_piercing", "metric": "largerHoleToBlankThreshold", "value": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:generic_press_piercing:largerHoleToHole', '2.0', NULL, 'Hole-spacing guidance (largerHoleToHole) for generic_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "generic_press_piercing", "metric": "largerHoleToHole", "value": 2.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:generic_press_piercing:largerHoleToHoleThreshold', '5.0', NULL, 'Hole-spacing guidance (largerHoleToHoleThreshold) for generic_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "generic_press_piercing", "metric": "largerHoleToHoleThreshold", "value": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:generic_press_piercing:smallerHoleToBlank', '1.5', NULL, 'Hole-spacing guidance (smallerHoleToBlank) for generic_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "generic_press_piercing", "metric": "smallerHoleToBlank", "value": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:generic_press_piercing:smallerHoleToHole', '1.5', NULL, 'Hole-spacing guidance (smallerHoleToHole) for generic_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "generic_press_piercing", "metric": "smallerHoleToHole", "value": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:progressive_die_piercing:holeToBend', '1.5', NULL, 'Hole-spacing guidance (holeToBend) for progressive_die_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "progressive_die_piercing", "metric": "holeToBend", "value": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:progressive_die_piercing:largerHoleToBlank', '2.0', NULL, 'Hole-spacing guidance (largerHoleToBlank) for progressive_die_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "progressive_die_piercing", "metric": "largerHoleToBlank", "value": 2.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:progressive_die_piercing:largerHoleToBlankThreshold', '5.0', NULL, 'Hole-spacing guidance (largerHoleToBlankThreshold) for progressive_die_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "progressive_die_piercing", "metric": "largerHoleToBlankThreshold", "value": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:progressive_die_piercing:largerHoleToHole', '2.0', NULL, 'Hole-spacing guidance (largerHoleToHole) for progressive_die_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "progressive_die_piercing", "metric": "largerHoleToHole", "value": 2.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:progressive_die_piercing:largerHoleToHoleThreshold', '5.0', NULL, 'Hole-spacing guidance (largerHoleToHoleThreshold) for progressive_die_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "progressive_die_piercing", "metric": "largerHoleToHoleThreshold", "value": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:progressive_die_piercing:smallerHoleToBlank', '1.5', NULL, 'Hole-spacing guidance (smallerHoleToBlank) for progressive_die_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "progressive_die_piercing", "metric": "smallerHoleToBlank", "value": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:progressive_die_piercing:smallerHoleToHole', '1.5', NULL, 'Hole-spacing guidance (smallerHoleToHole) for progressive_die_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "progressive_die_piercing", "metric": "smallerHoleToHole", "value": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:standard_press_piercing:holeToBend', '1.5', NULL, 'Hole-spacing guidance (holeToBend) for standard_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "standard_press_piercing", "metric": "holeToBend", "value": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:standard_press_piercing:largerHoleToBlank', '2.0', NULL, 'Hole-spacing guidance (largerHoleToBlank) for standard_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "standard_press_piercing", "metric": "largerHoleToBlank", "value": 2.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:standard_press_piercing:largerHoleToBlankThreshold', '5.0', NULL, 'Hole-spacing guidance (largerHoleToBlankThreshold) for standard_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "standard_press_piercing", "metric": "largerHoleToBlankThreshold", "value": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:standard_press_piercing:largerHoleToHole', '2.0', NULL, 'Hole-spacing guidance (largerHoleToHole) for standard_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "standard_press_piercing", "metric": "largerHoleToHole", "value": 2.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:standard_press_piercing:largerHoleToHoleThreshold', '5.0', NULL, 'Hole-spacing guidance (largerHoleToHoleThreshold) for standard_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "standard_press_piercing", "metric": "largerHoleToHoleThreshold", "value": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:standard_press_piercing:smallerHoleToBlank', '1.5', NULL, 'Hole-spacing guidance (smallerHoleToBlank) for standard_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "standard_press_piercing", "metric": "smallerHoleToBlank", "value": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:standard_press_piercing:smallerHoleToHole', '1.5', NULL, 'Hole-spacing guidance (smallerHoleToHole) for standard_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "standard_press_piercing", "metric": "smallerHoleToHole", "value": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:tandem_press_piercing:holeToBend', '1.5', NULL, 'Hole-spacing guidance (holeToBend) for tandem_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "tandem_press_piercing", "metric": "holeToBend", "value": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:tandem_press_piercing:largerHoleToBlank', '2.0', NULL, 'Hole-spacing guidance (largerHoleToBlank) for tandem_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "tandem_press_piercing", "metric": "largerHoleToBlank", "value": 2.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:tandem_press_piercing:largerHoleToBlankThreshold', '5.0', NULL, 'Hole-spacing guidance (largerHoleToBlankThreshold) for tandem_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "tandem_press_piercing", "metric": "largerHoleToBlankThreshold", "value": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:tandem_press_piercing:largerHoleToHole', '2.0', NULL, 'Hole-spacing guidance (largerHoleToHole) for tandem_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "tandem_press_piercing", "metric": "largerHoleToHole", "value": 2.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:tandem_press_piercing:largerHoleToHoleThreshold', '5.0', NULL, 'Hole-spacing guidance (largerHoleToHoleThreshold) for tandem_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "tandem_press_piercing", "metric": "largerHoleToHoleThreshold", "value": 5.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:tandem_press_piercing:smallerHoleToBlank', '1.5', NULL, 'Hole-spacing guidance (smallerHoleToBlank) for tandem_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "tandem_press_piercing", "metric": "smallerHoleToBlank", "value": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:tandem_press_piercing:smallerHoleToHole', '1.5', NULL, 'Hole-spacing guidance (smallerHoleToHole) for tandem_press_piercing -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "tandem_press_piercing", "metric": "smallerHoleToHole", "value": 1.5}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:other:holeToBend', '1.0', NULL, 'Hole-spacing guidance (holeToBend) for other -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "other", "metric": "holeToBend", "value": 1.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:other:holeToBlank', '1.0', NULL, 'Hole-spacing guidance (holeToBlank) for other -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "other", "metric": "holeToBlank", "value": 1.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:other:holeToHole', '1.0', NULL, 'Hole-spacing guidance (holeToHole) for other -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "other", "metric": "holeToHole", "value": 1.0}'::jsonb),
('lookup_table', 'USA', '2026-03', 'holeGuidance:other:uniqueHoleSizesMax', '1.0', NULL, 'Hole-spacing guidance (uniqueHoleSizesMax) for other -- cross-check against this app''s own DFM thresholds noted in migration 515 header', '{"group": "other", "metric": "uniqueHoleSizesMax", "value": 1.0}'::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;
