-- ============================================================================
-- Migration: Operation Name Reference -- friendly labels for the
--            Process:Operation//FeatureType taxonomy (staging)
-- Purpose: Lands the "tblDTCOperationNameReference" export (47 rows) into
--          the same lossless staging table earlier migrations created. See
--          migration 479's header for the staging/promotion architecture.
--          Source name sanitized per the standing rule against naming the
--          licensed source.
--
--          Maps a human-readable group label (e.g. "Combi Perforating") to
--          the exact fine-grained taxonomy string already staged in
--          migration 501 (e.g. "Laser Punch:Perforating:Perforating//
--          ComplexHole") -- purely a display/labeling convenience layer, not
--          new manufacturing data. No known consumer in this app yet (the
--          391-row taxonomy itself isn't surfaced in any UI beyond the
--          keyPattern-based Reference Data panels' raw key text).
-- Author: Principal Engineering Team
-- Date: 2026-08-20
-- Version: 1.0.0
-- ============================================================================

INSERT INTO sm_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('lookup_table', 'USA', '2026-03', 'operationNameReference:3D Laser:3D Laser Cutting//ComplexHole', '3D Laser Cutting', NULL, 'Friendly display-name grouping (''3D Laser Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "3D Laser Cutting", "operation_name": "3D Laser:3D Laser Cutting//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:3D Laser:3D Laser Cutting//SimpleHole', '3D Laser Cutting', NULL, 'Friendly display-name grouping (''3D Laser Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "3D Laser Cutting", "operation_name": "3D Laser:3D Laser Cutting//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Bend Brake:Bending/Form', 'Bend Brake', NULL, 'Friendly display-name grouping (''Bend Brake'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Bend Brake", "operation_name": "Bend Brake:Bending/Form"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Bend Brake:Bending//MultiBend', 'Bend Brake', NULL, 'Friendly display-name grouping (''Bend Brake'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Bend Brake", "operation_name": "Bend Brake:Bending//MultiBend"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Bend Brake:Bending//StraightBend', 'Bend Brake', NULL, 'Friendly display-name grouping (''Bend Brake'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Bend Brake", "operation_name": "Bend Brake:Bending//StraightBend"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Laser Punch:Perforating:Perforating//ComplexHole', 'Combi Perforating', NULL, 'Friendly display-name grouping (''Combi Perforating'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Combi Perforating", "operation_name": "Laser Punch:Perforating:Perforating//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Laser Punch:Perforating:Perforating//SimpleHole', 'Combi Perforating', NULL, 'Friendly display-name grouping (''Combi Perforating'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Combi Perforating", "operation_name": "Laser Punch:Perforating:Perforating//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Plasma Punch:Perforating:Perforating//ComplexHole', 'Combi Perforating', NULL, 'Friendly display-name grouping (''Combi Perforating'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Combi Perforating", "operation_name": "Plasma Punch:Perforating:Perforating//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Plasma Punch:Perforating:Perforating//SimpleHole', 'Combi Perforating', NULL, 'Friendly display-name grouping (''Combi Perforating'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Combi Perforating", "operation_name": "Plasma Punch:Perforating:Perforating//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Laser Punch:Nibbling:Nibbling//ComplexHole', 'Combi Punch', NULL, 'Friendly display-name grouping (''Combi Punch'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Combi Punch", "operation_name": "Laser Punch:Nibbling:Nibbling//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Laser Punch:Nibbling:Nibbling//SimpleHole', 'Combi Punch', NULL, 'Friendly display-name grouping (''Combi Punch'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Combi Punch", "operation_name": "Laser Punch:Nibbling:Nibbling//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Laser Punch:Punching:Punching//ComplexHole', 'Combi Punch', NULL, 'Friendly display-name grouping (''Combi Punch'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Combi Punch", "operation_name": "Laser Punch:Punching:Punching//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Laser Punch:Punching:Punching//SimpleHole', 'Combi Punch', NULL, 'Friendly display-name grouping (''Combi Punch'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Combi Punch", "operation_name": "Laser Punch:Punching:Punching//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Plasma Punch:Nibbling:Nibbling//ComplexHole', 'Combi Punch', NULL, 'Friendly display-name grouping (''Combi Punch'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Combi Punch", "operation_name": "Plasma Punch:Nibbling:Nibbling//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Plasma Punch:Nibbling:Nibbling//SimpleHole', 'Combi Punch', NULL, 'Friendly display-name grouping (''Combi Punch'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Combi Punch", "operation_name": "Plasma Punch:Nibbling:Nibbling//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Plasma Punch:Punching:Punching//ComplexHole', 'Combi Punch', NULL, 'Friendly display-name grouping (''Combi Punch'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Combi Punch", "operation_name": "Plasma Punch:Punching:Punching//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Plasma Punch:Punching:Punching//SimpleHole', 'Combi Punch', NULL, 'Friendly display-name grouping (''Combi Punch'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Combi Punch", "operation_name": "Plasma Punch:Punching:Punching//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Generic Press:Piercing//ComplexHole', 'Generic Press Piercing', NULL, 'Friendly display-name grouping (''Generic Press Piercing'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Generic Press Piercing", "operation_name": "Generic Press:Piercing//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Generic Press:Piercing//SimpleHole', 'Generic Press Piercing', NULL, 'Friendly display-name grouping (''Generic Press Piercing'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Generic Press Piercing", "operation_name": "Generic Press:Piercing//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Fiber Laser Cut:Fiber Laser Cutting//ComplexHole', 'Laser Cutting', NULL, 'Friendly display-name grouping (''Laser Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Laser Cutting", "operation_name": "Fiber Laser Cut:Fiber Laser Cutting//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Fiber Laser Cut:Fiber Laser Cutting//SimpleHole', 'Laser Cutting', NULL, 'Friendly display-name grouping (''Laser Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Laser Cutting", "operation_name": "Fiber Laser Cut:Fiber Laser Cutting//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Laser Cut:Laser Cutting//ComplexHole', 'Laser Cutting', NULL, 'Friendly display-name grouping (''Laser Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Laser Cutting", "operation_name": "Laser Cut:Laser Cutting//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Laser Cut:Laser Cutting//SimpleHole', 'Laser Cutting', NULL, 'Friendly display-name grouping (''Laser Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Laser Cutting", "operation_name": "Laser Cut:Laser Cutting//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Laser Punch:Laser Cut:Laser Cutting//ComplexHole', 'Laser Cutting', NULL, 'Friendly display-name grouping (''Laser Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Laser Cutting", "operation_name": "Laser Punch:Laser Cut:Laser Cutting//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Laser Punch:Laser Cut:Laser Cutting//SimpleHole', 'Laser Cutting', NULL, 'Friendly display-name grouping (''Laser Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Laser Cutting", "operation_name": "Laser Punch:Laser Cut:Laser Cutting//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:OxyFuel Cut:OxyFuel Cutting//ComplexHole', 'Oxyfuel Cutting', NULL, 'Friendly display-name grouping (''Oxyfuel Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Oxyfuel Cutting", "operation_name": "OxyFuel Cut:OxyFuel Cutting//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:OxyFuel Cut:OxyFuel Cutting//SimpleHole', 'Oxyfuel Cutting', NULL, 'Friendly display-name grouping (''Oxyfuel Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Oxyfuel Cutting", "operation_name": "OxyFuel Cut:OxyFuel Cutting//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Plasma Cut:Plasma Cutting//ComplexHole', 'Plasma Cutting', NULL, 'Friendly display-name grouping (''Plasma Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Plasma Cutting", "operation_name": "Plasma Cut:Plasma Cutting//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Plasma Cut:Plasma Cutting//SimpleHole', 'Plasma Cutting', NULL, 'Friendly display-name grouping (''Plasma Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Plasma Cutting", "operation_name": "Plasma Cut:Plasma Cutting//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Plasma Punch:Plasma Cut:Plasma Cutting//ComplexHole', 'Plasma Cutting', NULL, 'Friendly display-name grouping (''Plasma Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Plasma Cutting", "operation_name": "Plasma Punch:Plasma Cut:Plasma Cutting//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Plasma Punch:Plasma Cut:Plasma Cutting//SimpleHole', 'Plasma Cutting', NULL, 'Friendly display-name grouping (''Plasma Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Plasma Cutting", "operation_name": "Plasma Punch:Plasma Cut:Plasma Cutting//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Progressive Die:Die Station:Cam Action Piercing//ComplexHole', 'Progressive Die Piercing', NULL, 'Friendly display-name grouping (''Progressive Die Piercing'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Progressive Die Piercing", "operation_name": "Progressive Die:Die Station:Cam Action Piercing//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Progressive Die:Die Station:Cam Action Piercing//SimpleHole', 'Progressive Die Piercing', NULL, 'Friendly display-name grouping (''Progressive Die Piercing'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Progressive Die Piercing", "operation_name": "Progressive Die:Die Station:Cam Action Piercing//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Progressive Die:Die Station:Piercing//ComplexHole', 'Progressive Die Piercing', NULL, 'Friendly display-name grouping (''Progressive Die Piercing'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Progressive Die Piercing", "operation_name": "Progressive Die:Die Station:Piercing//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Progressive Die:Die Station:Piercing//SimpleHole', 'Progressive Die Piercing', NULL, 'Friendly display-name grouping (''Progressive Die Piercing'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Progressive Die Piercing", "operation_name": "Progressive Die:Die Station:Piercing//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:2 Axis Router:Router Cutting//ComplexHole', 'Router', NULL, 'Friendly display-name grouping (''Router'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Router", "operation_name": "2 Axis Router:Router Cutting//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:2 Axis Router:Router Cutting//SimpleHole', 'Router', NULL, 'Friendly display-name grouping (''Router'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Router", "operation_name": "2 Axis Router:Router Cutting//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Std Press:Std Press//ComplexHole', 'Standard Press Piercing', NULL, 'Friendly display-name grouping (''Standard Press Piercing'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Standard Press Piercing", "operation_name": "Std Press:Std Press//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Std Press:Std Press//SimpleHole', 'Standard Press Piercing', NULL, 'Friendly display-name grouping (''Standard Press Piercing'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Standard Press Piercing", "operation_name": "Std Press:Std Press//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Tandem Press:Piercing//ComplexHole', 'Tandem Press Piercing', NULL, 'Friendly display-name grouping (''Tandem Press Piercing'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Tandem Press Piercing", "operation_name": "Tandem Press:Piercing//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Tandem Press:Piercing//SimpleHole', 'Tandem Press Piercing', NULL, 'Friendly display-name grouping (''Tandem Press Piercing'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Tandem Press Piercing", "operation_name": "Tandem Press:Piercing//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Turret Press:Perforating:Perforating//ComplexHole', 'Turret Perforating', NULL, 'Friendly display-name grouping (''Turret Perforating'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Turret Perforating", "operation_name": "Turret Press:Perforating:Perforating//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Turret Press:Perforating:Perforating//SimpleHole', 'Turret Perforating', NULL, 'Friendly display-name grouping (''Turret Perforating'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Turret Perforating", "operation_name": "Turret Press:Perforating:Perforating//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Turret Press:Punching:Punching//ComplexHole', 'Turret Punch', NULL, 'Friendly display-name grouping (''Turret Punch'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Turret Punch", "operation_name": "Turret Press:Punching:Punching//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Turret Press:Punching:Punching//SimpleHole', 'Turret Punch', NULL, 'Friendly display-name grouping (''Turret Punch'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Turret Punch", "operation_name": "Turret Press:Punching:Punching//SimpleHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Waterjet Cut:Waterjet Cutting//ComplexHole', 'Waterjet Cutting', NULL, 'Friendly display-name grouping (''Waterjet Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Waterjet Cutting", "operation_name": "Waterjet Cut:Waterjet Cutting//ComplexHole"}'::jsonb),
('lookup_table', 'USA', '2026-03', 'operationNameReference:Waterjet Cut:Waterjet Cutting//SimpleHole', 'Waterjet Cutting', NULL, 'Friendly display-name grouping (''Waterjet Cutting'') for the fine-grained Process:Operation//FeatureType taxonomy string (migration 501) -- no known consumer in this app yet', '{"operation_name_reference": "Waterjet Cutting", "operation_name": "Waterjet Cut:Waterjet Cutting//SimpleHole"}'::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;
