-- ============================================================================
-- Migration 585: Seed "Standard Press" -- a real, previously-missing
-- machine_library.json category (16 machines staged; only 4 genuinely new)
--
-- Context: source is uploaded Standard Press fleet screenshots. Flattened to
-- this file's established convention (labor_rate_usd_per_hr ->
-- labor_rate_usd_hr, press_force_kN -> press_force_kn, machine_power_kW ->
-- machine_power_kw, machine_uptime_factor_pct -> machine_uptime_pct,
-- supplies_cost_usd_per_yr -> supplies_cost_usd_yr, and
-- constant_coefficient_handling_time / mass_coefficient_handling_time_s_per_kg
-- -> const_coeff_handling_time / mass_coeff_handling_time_s_kg, matching the
-- exact field names Progressive Die Press already uses for the identical
-- concept). primary_id and wage_grade_name are null in the source -- left
-- null, not invented.
--
-- DUPLICATE CHECK (done before writing this, live 2026-08-27): 12 of the 16
-- machines (Default Press, Schuler 1150 Ton, Schuler A2/200 - 360, Schuler
-- TSD 2000, and all 8 United Power SHD/SHS/THD variants) are the SAME
-- physical machines already in mhr_records under 'Progressive Die Press' and
-- 'Tandem Press' -- identical machine_price_usd and Direct/Indirect OH
-- confirmed by direct query. All 16 are staged into sm_reference_data for a
-- lossless record (matching how every prior category stages its full source
-- regardless of cross-category duplication), but the promotion step's
-- existing by-name dedup (migration 564's own query, unmodified) will skip
-- all 12 automatically -- expect exactly 4 new mhr_records rows from this
-- migration, not 16.
--
-- The remaining 4 ('Standard Press - 1,500/3,000/5,000/7,000kN Press Force')
-- are genuinely new: same Direct/Indirect OH as the equivalent Progressive
-- Die Press / Tandem Press tonnage tier (a shared press-force-tier rate
-- convention across the whole Press/Forming family) but a DIFFERENT
-- machine_price_usd per tier -- a real, distinct category, matching
-- CLAUDE.md's own "Press/Forming family (Generic/Std/Tandem Press -- taxonomy
-- exists, unwired placeholders)" three-way split.
--
-- Taxonomy linking -- identity only, matching migration 572's own precedent:
-- process_calculator_mappings already has a real 'Std Press' operation
-- (Bending/Floating /Forming route) but is_active=false with machine_class
-- NULL (confirmed live, 2026-08-27). process_route/operation populated for
-- real, honest reporting; machine_class deliberately left NULL, same
-- discipline as migration 572's 2-Axis Router/Oxyfuel/Tandem Press rows and
-- migration 584's Plasma Punch row.
-- ============================================================================
-- CORRECTION (2026-08-27, before this migration was ever run): the 4 new
-- 'Standard Press - X,000kN Press Force' rows' physical/capex block
-- (press_force_kn, machine_price_usd, machine_length_mm, machine_width_mm,
-- machine_power_kw) below has been corrected against a second
-- transcription of the same source screenshots (press_machine_staging.json)
-- -- the original standard_press_machine_data.json had every one of its 16
-- machines' physical/capex block reassigned to a DIFFERENT machine's values
-- (a row-alignment error), confirmed by diffing both files field-by-field.
-- User confirmed press_machine_staging.json's pairing is correct. Direct/
-- Indirect OH and price for these 4 tiers now exactly match Progressive Die
-- Press's own tiers of the same tonnage -- consistent with a shared
-- reference-benchmark convention across the Press/Forming family, not a
-- further conflict. The other 12 machines (already-known Progressive Die
-- Press/Tandem Press duplicates, never promoted) are unaffected.
--
-- SECOND CORRECTION (2026-08-27, after this migration had already been run
-- live once): a 4th transcription (std_press.json) of these same 4 machines
-- matched the ORIGINAL standard_press_machine_data.json pairing exactly --
-- tying the vote 2-2 against the "corrected" pairing above (which had 2
-- files agreeing: press_machine_staging.json and stage_press.json). Direct/
-- Indirect OH were identical across every transcription throughout and were
-- never in question -- only the physical/capex block (price, press force,
-- dimensions, power) was ever in dispute. User decided the tie in favor of
-- the ORIGINAL pairing; the values below are reverted back to it. Migration
-- 586 updates the already-promoted mhr_records rows to match (this file's
-- own values only matter for a future fresh-DB run). Step 1b's separate
-- 'Standard Press (staging)' audit copy of press_machine_staging.json is
-- deliberately left untouched below -- it is a faithful record of that one
-- file's own transcription, not a claim about which pairing is correct.
-- ============================================================================

BEGIN;

-- Step 1: Stage all 16 into sm_reference_data (lossless; dedup happens at promotion)
INSERT INTO sm_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('machine', 'Shop Fleet', '2026-08', 'Standard Press:Default Press', '105000', 'Currency', 'Standard Press reference spec', '{"name": "Default Press", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 28.0, "indirect_overhead_rate_usd_hr": 16.33, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.3, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 3.6, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 703.0, "max_part_width_mm": 701.04, "press_force_kn": 1654.0, "pitch_margin_mm": 0, "side_margin_mm": 0, "trim_strip_width_mm": 6, "max_thickness_aluminum_mm": 31, "max_thickness_brass_mm": 30, "max_thickness_copper_mm": 31, "max_thickness_stainless_steel_mm": 23, "max_thickness_steel_mm": 25, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 105000, "machine_length_mm": 1757.5, "machine_width_mm": 2804.16, "footprint_allowance_factor": 3.0, "machine_power_kw": 14.91, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "USA", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:Schuler 1150 Ton', '200000', 'Currency', 'Standard Press reference spec', '{"name": "Schuler 1150 Ton", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 72.61, "indirect_overhead_rate_usd_hr": 19.94, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.3, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 3.0, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 914.4, "max_part_width_mm": 609.6, "press_force_kn": 658.0, "pitch_margin_mm": 0, "side_margin_mm": 0, "trim_strip_width_mm": 6, "max_thickness_aluminum_mm": 19, "max_thickness_brass_mm": 18, "max_thickness_copper_mm": 19, "max_thickness_stainless_steel_mm": 14, "max_thickness_steel_mm": 15, "is_preferred": true, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 200000, "machine_length_mm": 2500.0, "machine_width_mm": 2800.0, "footprint_allowance_factor": 3.0, "machine_power_kw": 30.0, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "Virtual", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:Schuler A2/200 - 360', '218000', 'Currency', 'Standard Press reference spec', '{"name": "Schuler A2/200 - 360", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 55.83, "indirect_overhead_rate_usd_hr": 15.89, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.3, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 3.0, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 1000.0, "max_part_width_mm": 700.0, "press_force_kn": 1500.0, "pitch_margin_mm": 0, "side_margin_mm": 0, "trim_strip_width_mm": 0, "max_thickness_aluminum_mm": 0, "max_thickness_brass_mm": 0, "max_thickness_copper_mm": 0, "max_thickness_stainless_steel_mm": 0, "max_thickness_steel_mm": 0, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 218000, "machine_length_mm": 2286.0, "machine_width_mm": 2438.4, "footprint_allowance_factor": 3.0, "machine_power_kw": 29.83, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "USA", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:Schuler TSD 2000', '264000', 'Currency', 'Standard Press reference spec', '{"name": "Schuler TSD 2000", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 248.15, "indirect_overhead_rate_usd_hr": 34.96, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 3.24, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 1300.48, "max_part_width_mm": 1198.88, "press_force_kn": 6636.0, "pitch_margin_mm": 6, "side_margin_mm": 6, "trim_strip_width_mm": 0, "max_thickness_aluminum_mm": 0, "max_thickness_brass_mm": 0, "max_thickness_copper_mm": 0, "max_thickness_stainless_steel_mm": 0, "max_thickness_steel_mm": 0, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 264000, "machine_length_mm": 1757.5, "machine_width_mm": 2804.16, "footprint_allowance_factor": 3.0, "machine_power_kw": 14.91, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "USA", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:Standard Press - 1,500kN Press Force', '318000', 'Currency', 'Standard Press reference spec', '{"name": "Standard Press - 1,500kN Press Force", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 16.64, "indirect_overhead_rate_usd_hr": 15.63, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 0.5, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 1320.8, "max_part_width_mm": 812.8, "press_force_kn": 1365.0, "pitch_margin_mm": 0, "side_margin_mm": 0, "trim_strip_width_mm": 6, "max_thickness_aluminum_mm": 112, "max_thickness_brass_mm": 108, "max_thickness_copper_mm": 112, "max_thickness_stainless_steel_mm": 0, "max_thickness_steel_mm": 0, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 318000, "machine_length_mm": 3000.0, "machine_width_mm": 3240.0, "footprint_allowance_factor": 3.0, "machine_power_kw": 57.88, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "USA", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:Standard Press - 3,000kN Press Force', '350000', 'Currency', 'Standard Press reference spec', '{"name": "Standard Press - 3,000kN Press Force", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 36.31, "indirect_overhead_rate_usd_hr": 16.49, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 2.0, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 1350.0, "max_part_width_mm": 1100.0, "press_force_kn": 5000.0, "pitch_margin_mm": 0, "side_margin_mm": 0, "trim_strip_width_mm": 6, "max_thickness_aluminum_mm": 20, "max_thickness_brass_mm": 19, "max_thickness_copper_mm": 20, "max_thickness_stainless_steel_mm": 83, "max_thickness_steel_mm": 90, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 350000, "machine_length_mm": 3601.72, "machine_width_mm": 3236.97, "footprint_allowance_factor": 3.0, "machine_power_kw": 22.37, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "USA", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:Standard Press - 5,000kN Press Force', '500000', 'Currency', 'Standard Press reference spec', '{"name": "Standard Press - 5,000kN Press Force", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 62.2, "indirect_overhead_rate_usd_hr": 17.44, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 2.8, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 1500.0, "max_part_width_mm": 1200.0, "press_force_kn": 2000.0, "pitch_margin_mm": 0, "side_margin_mm": 0, "trim_strip_width_mm": 6, "max_thickness_aluminum_mm": 112, "max_thickness_brass_mm": 108, "max_thickness_copper_mm": 112, "max_thickness_stainless_steel_mm": 15, "max_thickness_steel_mm": 16, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 500000, "machine_length_mm": 3200.0, "machine_width_mm": 3240.0, "footprint_allowance_factor": 3.0, "machine_power_kw": 40.0, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "Virtual", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:Standard Press - 7,000kN Press Force', '529000', 'Currency', 'Standard Press reference spec', '{"name": "Standard Press - 7,000kN Press Force", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 83.0, "indirect_overhead_rate_usd_hr": 22.39, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 3.0, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 1600.0, "max_part_width_mm": 1200.0, "press_force_kn": 3000.0, "pitch_margin_mm": 0, "side_margin_mm": 0, "trim_strip_width_mm": 6, "max_thickness_aluminum_mm": 112, "max_thickness_brass_mm": 108, "max_thickness_copper_mm": 112, "max_thickness_stainless_steel_mm": 83, "max_thickness_steel_mm": 90, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 529000, "machine_length_mm": 3454.4, "machine_width_mm": 2743.2, "footprint_allowance_factor": 3.0, "machine_power_kw": 44.74, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "Virtual", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:United Power SHD-220 Ton', '636000', 'Currency', 'Standard Press reference spec', '{"name": "United Power SHD-220 Ton", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 24.57, "indirect_overhead_rate_usd_hr": 16.82, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.3, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 4.0, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 1727.2, "max_part_width_mm": 1016.0, "press_force_kn": 3318.0, "pitch_margin_mm": 6, "side_margin_mm": 6, "trim_strip_width_mm": 0, "max_thickness_aluminum_mm": 38, "max_thickness_brass_mm": 36, "max_thickness_copper_mm": 38, "max_thickness_stainless_steel_mm": 28, "max_thickness_steel_mm": 30, "is_preferred": true, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 636000, "machine_length_mm": 4500.88, "machine_width_mm": 3511.3, "footprint_allowance_factor": 3.0, "machine_power_kw": 37.29, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "USA", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:United Power SHD-400 Ton', '798000', 'Currency', 'Standard Press reference spec', '{"name": "United Power SHD-400 Ton", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 44.13, "indirect_overhead_rate_usd_hr": 17.89, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.3, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 2.6, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 1800.86, "max_part_width_mm": 1198.88, "press_force_kn": 2192.0, "pitch_margin_mm": 0, "side_margin_mm": 0, "trim_strip_width_mm": 6, "max_thickness_aluminum_mm": 0, "max_thickness_brass_mm": 0, "max_thickness_copper_mm": 0, "max_thickness_stainless_steel_mm": 0, "max_thickness_steel_mm": 0, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 798000, "machine_length_mm": 2700.0, "machine_width_mm": 2970.0, "footprint_allowance_factor": 3.0, "machine_power_kw": 30.0, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "USA", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:United Power SHD-666 Ton', '850000', 'Currency', 'Standard Press reference spec', '{"name": "United Power SHD-666 Ton", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 72.84, "indirect_overhead_rate_usd_hr": 19.03, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.3, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 2.6, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 2000.0, "max_part_width_mm": 1300.0, "press_force_kn": 5000.0, "pitch_margin_mm": 0, "side_margin_mm": 0, "trim_strip_width_mm": 6, "max_thickness_aluminum_mm": 63, "max_thickness_brass_mm": 60, "max_thickness_copper_mm": 63, "max_thickness_stainless_steel_mm": 46, "max_thickness_steel_mm": 50, "is_preferred": true, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 850000, "machine_length_mm": 4000.0, "machine_width_mm": 3510.0, "footprint_allowance_factor": 3.0, "machine_power_kw": 50.0, "installation_factor_pct": 30, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 3, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "Germany", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:United Power SHS-166 Ton', '1060000', 'Currency', 'Standard Press reference spec', '{"name": "United Power SHS-166 Ton", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 18.23, "indirect_overhead_rate_usd_hr": 15.1, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.3, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 3.0, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 2250.44, "max_part_width_mm": 1300.48, "press_force_kn": 4000.0, "pitch_margin_mm": 0, "side_margin_mm": 6, "trim_strip_width_mm": 0, "max_thickness_aluminum_mm": 40, "max_thickness_brass_mm": 38, "max_thickness_copper_mm": 40, "max_thickness_stainless_steel_mm": 29, "max_thickness_steel_mm": 32, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 1060000, "machine_length_mm": 2600.96, "machine_width_mm": 3236.98, "footprint_allowance_factor": 3.0, "machine_power_kw": 74.57, "installation_factor_pct": 30, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 3, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "Virtual", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:United Power SHS-666 Ton', '1060000', 'Currency', 'Standard Press reference spec', '{"name": "United Power SHS-666 Ton", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 72.84, "indirect_overhead_rate_usd_hr": 15.99, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.3, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 2.6, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 2499.36, "max_part_width_mm": 1501.14, "press_force_kn": 6636.0, "pitch_margin_mm": 0, "side_margin_mm": 0, "trim_strip_width_mm": 0, "max_thickness_aluminum_mm": 80, "max_thickness_brass_mm": 77, "max_thickness_copper_mm": 80, "max_thickness_stainless_steel_mm": 0, "max_thickness_steel_mm": 0, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 1060000, "machine_length_mm": 4998.72, "machine_width_mm": 4053.08, "footprint_allowance_factor": 3.0, "machine_power_kw": 74.57, "installation_factor_pct": 30, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 3, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "USA", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:United Power THD-137 High Speed', '1120000', 'Currency', 'Standard Press reference spec', '{"name": "United Power THD-137 High Speed", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 17.7, "indirect_overhead_rate_usd_hr": 15.26, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.3, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 0.32, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 3250.0, "max_part_width_mm": 1900.0, "press_force_kn": 7000.0, "pitch_margin_mm": 0, "side_margin_mm": 0, "trim_strip_width_mm": 6, "max_thickness_aluminum_mm": 112, "max_thickness_brass_mm": 108, "max_thickness_copper_mm": 112, "max_thickness_stainless_steel_mm": 59, "max_thickness_steel_mm": 64, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 1120000, "machine_length_mm": 6807.2, "machine_width_mm": 3497.58, "footprint_allowance_factor": 3.0, "machine_power_kw": 50.0, "installation_factor_pct": 30, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 3, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "USA", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:United Power THD-333 High Speed', '1150000', 'Currency', 'Standard Press reference spec', '{"name": "United Power THD-333 High Speed", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 38.78, "indirect_overhead_rate_usd_hr": 16.26, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.3, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 0.6, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 3403.6, "max_part_width_mm": 1900.0, "press_force_kn": 7000.0, "pitch_margin_mm": 6, "side_margin_mm": 0, "trim_strip_width_mm": 6, "max_thickness_aluminum_mm": 0, "max_thickness_brass_mm": 0, "max_thickness_copper_mm": 0, "max_thickness_stainless_steel_mm": 0, "max_thickness_steel_mm": 90, "is_preferred": true, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 1150000, "machine_length_mm": 6500.0, "machine_width_mm": 5130.0, "footprint_allowance_factor": 3.0, "machine_power_kw": 60.0, "installation_factor_pct": 30, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 3, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "Germany", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press:United Power THD-66 High Speed', '3600000', 'Currency', 'Standard Press reference spec', '{"name": "United Power THD-66 High Speed", "labor_rate_usd_hr": 36.3, "direct_overhead_rate_usd_hr": 8.61, "indirect_overhead_rate_usd_hr": 15.1, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.3, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 0.32, "const_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_kg": 0.03, "max_part_length_mm": 6100.0, "max_part_width_mm": 2500.0, "press_force_kn": 20000.0, "pitch_margin_mm": 6, "side_margin_mm": 0, "trim_strip_width_mm": 0, "max_thickness_aluminum_mm": 112, "max_thickness_brass_mm": 108, "max_thickness_copper_mm": 112, "max_thickness_stainless_steel_mm": 83, "max_thickness_steel_mm": 90, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 3600000, "machine_length_mm": 12200.0, "machine_width_mm": 6750.0, "footprint_allowance_factor": 3.0, "machine_power_kw": 200.0, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplies_cost_usd_yr": 0.0, "machine_manufacturer_location": "Virtual", "data_source": "Uploaded Standard Press machine fleet screenshots", "machine_category": "Standard Press"}'::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

-- Step 1b: Also stage press_machine_staging.json's own 16 rows as a SEPARATE
-- audit-trail copy, under a distinct key prefix ('Standard Press (staging)').
-- This is the second transcription of the same source screenshots used to
-- correct the 4 new rows above (see the correction note at the top of this
-- file) -- staged here in full, faithfully (its own field names kept as-is,
-- including primary_id/process/manufacturer_location/supplier_cost_usd_per_yr),
-- matching every other category's lossless-staging convention rather than
-- letting this transcription exist only as an unstaged correction input.
-- Deliberately NOT promoted into mhr_records (the key prefix does not match
-- 'Standard Press:%%', so Step 2's promotion query below cannot pick it up) --
-- reference/audit only.
INSERT INTO sm_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):Default Press', '318000.0', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "default_press", "name": "Default Press", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 28.0, "indirect_overhead_rate_usd_per_hr": 16.33, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 3.6, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 1500.0, "max_part_width_mm": 1200.0, "press_force_kn": 2000.0, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 38.0, "max_thickness_brass_mm": 36.0, "max_thickness_copper_mm": 38.0, "max_thickness_steel_mm": 28.0, "max_thickness_stainless_steel_mm": 30.0, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 318000.0, "machine_length_mm": 3000.0, "machine_width_mm": 3240.0, "footprint_allowance_factor": 3.0, "machine_power_kw": 57.88, "installation_factor_pct": 20.0, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5.0, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "USA", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):Schuler 1150 Ton', '1120000.0', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "schuler_1150_ton", "name": "Schuler 1150 Ton", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 72.61, "indirect_overhead_rate_usd_per_hr": 19.94, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 3.0, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 3403.6, "max_part_width_mm": 1295.4, "press_force_kn": 7000.0, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 112.0, "max_thickness_brass_mm": 108.0, "max_thickness_copper_mm": 112.0, "max_thickness_steel_mm": 83.0, "max_thickness_stainless_steel_mm": 90.0, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 1120000.0, "machine_length_mm": 6807.2, "machine_width_mm": 3497.58, "footprint_allowance_factor": 3.0, "machine_power_kw": 50.0, "installation_factor_pct": 30.0, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 3.0, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "Germany", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):Schuler A2/200 - 360', '798000.0', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "schuler_a2_200_360", "name": "Schuler A2/200 - 360", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 55.83, "indirect_overhead_rate_usd_per_hr": 15.89, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 3.0, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 1350.0, "max_part_width_mm": 1100.0, "press_force_kn": 5000.0, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 112.0, "max_thickness_brass_mm": 108.0, "max_thickness_copper_mm": 112.0, "max_thickness_steel_mm": 83.0, "max_thickness_stainless_steel_mm": 90.0, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 798000.0, "machine_length_mm": 2700.0, "machine_width_mm": 2970.0, "footprint_allowance_factor": 3.0, "machine_power_kw": 30.0, "installation_factor_pct": 30.0, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5.0, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "Germany", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):Schuler TSD 2000', '3600000.0', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "schuler_tsd_2000", "name": "Schuler TSD 2000", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 248.15, "indirect_overhead_rate_usd_per_hr": 34.96, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 3.24, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 6100.0, "max_part_width_mm": 2500.0, "press_force_kn": 20000.0, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 112.0, "max_thickness_brass_mm": 108.0, "max_thickness_copper_mm": 112.0, "max_thickness_steel_mm": 83.0, "max_thickness_stainless_steel_mm": 90.0, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 3600000.0, "machine_length_mm": 12200.0, "machine_width_mm": 6750.0, "footprint_allowance_factor": 3.0, "machine_power_kw": 200.0, "installation_factor_pct": 20.0, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5.0, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "Germany", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):Standard Press - 1,500kN Press Force', '200000', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "standard_press_1500kn", "name": "Standard Press - 1,500kN Press Force", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 16.64, "indirect_overhead_rate_usd_per_hr": 15.63, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 0.5, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 1000, "max_part_width_mm": 700, "press_force_kn": 1500, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 0, "max_thickness_brass_mm": 0, "max_thickness_copper_mm": 0, "max_thickness_steel_mm": 0, "max_thickness_stainless_steel_mm": 0, "is_preferred": true, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 200000, "machine_length_mm": 2500, "machine_width_mm": 2800, "footprint_allowance_factor": 3.0, "machine_power_kw": 30, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "Virtual", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):Standard Press - 3,000kN Press Force', '500000', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "standard_press_3000kn", "name": "Standard Press - 3,000kN Press Force", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 36.31, "indirect_overhead_rate_usd_per_hr": 16.49, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 2.0, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 1600, "max_part_width_mm": 1200, "press_force_kn": 3000, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 0, "max_thickness_brass_mm": 0, "max_thickness_copper_mm": 0, "max_thickness_steel_mm": 0, "max_thickness_stainless_steel_mm": 0, "is_preferred": true, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 500000, "machine_length_mm": 3200, "machine_width_mm": 3240, "footprint_allowance_factor": 3.0, "machine_power_kw": 40, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "Virtual", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):Standard Press - 5,000kN Press Force', '850000', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "standard_press_5000kn", "name": "Standard Press - 5,000kN Press Force", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 62.2, "indirect_overhead_rate_usd_per_hr": 17.44, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 2.8, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 2000, "max_part_width_mm": 1300, "press_force_kn": 5000, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 0, "max_thickness_brass_mm": 0, "max_thickness_copper_mm": 0, "max_thickness_steel_mm": 0, "max_thickness_stainless_steel_mm": 0, "is_preferred": true, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 850000, "machine_length_mm": 4000, "machine_width_mm": 3510, "footprint_allowance_factor": 3.0, "machine_power_kw": 50, "installation_factor_pct": 30, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "Virtual", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):Standard Press - 7,000kN Press Force', '1150000', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "standard_press_7000kn", "name": "Standard Press - 7,000kN Press Force", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 83.0, "indirect_overhead_rate_usd_per_hr": 22.39, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 3.0, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 3250, "max_part_width_mm": 1900, "press_force_kn": 7000, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 0, "max_thickness_brass_mm": 0, "max_thickness_copper_mm": 0, "max_thickness_steel_mm": 0, "max_thickness_stainless_steel_mm": 0, "is_preferred": true, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 1150000, "machine_length_mm": 6500, "machine_width_mm": 5130, "footprint_allowance_factor": 3.0, "machine_power_kw": 60, "installation_factor_pct": 30, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "Virtual", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):United Power SHD-220 Ton', '350000', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "united_power_shd_220", "name": "United Power SHD-220 Ton", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 24.57, "indirect_overhead_rate_usd_per_hr": 16.82, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 4.0, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 1800.86, "max_part_width_mm": 1198.88, "press_force_kn": 2192, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 40, "max_thickness_brass_mm": 38, "max_thickness_copper_mm": 40, "max_thickness_steel_mm": 29, "max_thickness_stainless_steel_mm": 32, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 350000, "machine_length_mm": 3601.72, "machine_width_mm": 3236.97, "footprint_allowance_factor": 3.0, "machine_power_kw": 22.37, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "USA", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):United Power SHD-400 Ton', '636000', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "united_power_shd_400", "name": "United Power SHD-400 Ton", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 44.13, "indirect_overhead_rate_usd_per_hr": 17.89, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 2.6, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 2250.44, "max_part_width_mm": 1300.48, "press_force_kn": 4000, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 80, "max_thickness_brass_mm": 77, "max_thickness_copper_mm": 80, "max_thickness_steel_mm": 59, "max_thickness_stainless_steel_mm": 64, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 636000, "machine_length_mm": 4500.88, "machine_width_mm": 3511.3, "footprint_allowance_factor": 3.0, "machine_power_kw": 37.29, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "USA", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):United Power SHD-666 Ton', '1060000', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "united_power_shd_666", "name": "United Power SHD-666 Ton", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 72.84, "indirect_overhead_rate_usd_per_hr": 19.03, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 2.6, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 2499.36, "max_part_width_mm": 1501.14, "press_force_kn": 6636, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 112, "max_thickness_brass_mm": 108, "max_thickness_copper_mm": 112, "max_thickness_steel_mm": 83, "max_thickness_stainless_steel_mm": 90, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 1060000, "machine_length_mm": 4998.72, "machine_width_mm": 4053.08, "footprint_allowance_factor": 3.0, "machine_power_kw": 74.57, "installation_factor_pct": 30, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 3, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "USA", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):United Power SHS-166 Ton', '264000', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "united_power_shs_166", "name": "United Power SHS-166 Ton", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 18.23, "indirect_overhead_rate_usd_per_hr": 15.1, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 3.0, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 703.0, "max_part_width_mm": 701.04, "press_force_kn": 1654, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 31, "max_thickness_brass_mm": 30, "max_thickness_copper_mm": 31, "max_thickness_steel_mm": 23, "max_thickness_stainless_steel_mm": 25, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 264000, "machine_length_mm": 1757.5, "machine_width_mm": 2804.16, "footprint_allowance_factor": 3.0, "machine_power_kw": 14.91, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "USA", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):United Power SHS-666 Ton', '1060000', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "united_power_shs_666", "name": "United Power SHS-666 Ton", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 72.84, "indirect_overhead_rate_usd_per_hr": 15.99, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 2.6, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 1300.48, "max_part_width_mm": 1198.88, "press_force_kn": 6636, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 112, "max_thickness_brass_mm": 108, "max_thickness_copper_mm": 112, "max_thickness_steel_mm": 83, "max_thickness_stainless_steel_mm": 90, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 1060000, "machine_length_mm": 2600.96, "machine_width_mm": 3236.98, "footprint_allowance_factor": 3.0, "machine_power_kw": 74.57, "installation_factor_pct": 30, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 3, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "USA", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):United Power THD-137 High Speed', '218000', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "united_power_thd_137", "name": "United Power THD-137 High Speed", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 17.7, "indirect_overhead_rate_usd_per_hr": 15.26, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 0.32, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 1320.8, "max_part_width_mm": 812.8, "press_force_kn": 1365, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 20, "max_thickness_brass_mm": 19, "max_thickness_copper_mm": 20, "max_thickness_steel_mm": 15, "max_thickness_stainless_steel_mm": 16, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 218000, "machine_length_mm": 2286.0, "machine_width_mm": 2438.4, "footprint_allowance_factor": 3.0, "machine_power_kw": 29.83, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "USA", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):United Power THD-333 High Speed', '529000', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "united_power_thd_333", "name": "United Power THD-333 High Speed", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 38.78, "indirect_overhead_rate_usd_per_hr": 16.26, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 0.6, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 1727.2, "max_part_width_mm": 1016.0, "press_force_kn": 3318, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 63, "max_thickness_brass_mm": 60, "max_thickness_copper_mm": 63, "max_thickness_steel_mm": 46, "max_thickness_stainless_steel_mm": 50, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 529000, "machine_length_mm": 3454.4, "machine_width_mm": 2743.2, "footprint_allowance_factor": 3.0, "machine_power_kw": 44.74, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "USA", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb),
('machine', 'Shop Fleet', '2026-08', 'Standard Press (staging):United Power THD-66 High Speed', '105000', 'Currency', 'Standard Press second-transcription audit copy (press_machine_staging.json) -- reference only, never promoted', '{"primary_id": "united_power_thd_66", "name": "United Power THD-66 High Speed", "process": "press", "labor_rate_usd_per_hr": 36.3, "direct_overhead_rate_usd_per_hr": 8.61, "indirect_overhead_rate_usd_per_hr": 15.1, "overhead_multiplier": 0.0, "number_of_operators": 1.0, "labor_time_standard": 1.0, "wage_grade_name": null, "work_center_labor_rate_factor": 1.0, "setup_time_hr": 0.5, "press_cycle_time_s": 0.32, "constant_coeff_handling_time": 0.0, "mass_coeff_handling_time_s_per_kg": 0.03, "max_part_length_mm": 914.4, "max_part_width_mm": 609.6, "press_force_kn": 658, "pitch_margin_mm": 6.0, "side_margin_mm": 6.0, "trim_strip_width_mm": 0.0, "max_thickness_aluminum_mm": 19, "max_thickness_brass_mm": 18, "max_thickness_copper_mm": 19, "max_thickness_steel_mm": 14, "max_thickness_stainless_steel_mm": 15, "is_preferred": false, "avg_utilization": 0.7, "good_part_yield": 1.0, "machine_price_usd": 105000, "machine_length_mm": 1757.5, "machine_width_mm": 2804.16, "footprint_allowance_factor": 3.0, "machine_power_kw": 14.91, "installation_factor_pct": 20, "machine_uptime_pct": 80.0, "annual_maintenance_factor_pct": 5, "machine_life_yr": 10, "salvage_value_factor_pct": 0.0, "supplier_cost_usd_per_yr": 0.0, "manufacturer_location": "USA", "data_source": "Digital Factory Manager screenshots", "schema": "press_machine_staging_v1"}'::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

-- Step 2: Promote into mhr_records (migration 564's exact dedup query,
-- unmodified -- expect 4 inserted, 12 skipped as already-present by name).
DO $$
DECLARE
  matched_count      INTEGER;
BEGIN
  WITH name_counts AS (
    SELECT lower(raw->>'name') AS name_lower, COUNT(*) AS cnt
    FROM sm_reference_data
    WHERE category = 'machine'
    GROUP BY lower(raw->>'name')
  ),
  unambiguous AS (
    SELECT sr.key, sr.raw
    FROM sm_reference_data sr
    JOIN name_counts c ON c.name_lower = lower(sr.raw->>'name')
    WHERE sr.category = 'machine' AND c.cnt = 1
  ),
  to_promote AS (
    SELECT u.key, u.raw
    FROM unambiguous u
    WHERE NOT EXISTS (
      SELECT 1 FROM mhr_records mr WHERE lower(mr.machine_name) = lower(u.raw->>'name')
    )
    AND u.key LIKE 'Standard Press:%'
  )
  INSERT INTO mhr_records (
    user_id, organization_id, location, commodity_code, process_group, machine_class,
    machine_name, machine_description, manufacturer_country, machine_price_usd,
    landed_machine_cost, is_manual_entry, manual_mhr_value, total_machine_hour_rate,
    fully_burdened_local_per_hr,
    shifts_per_day, hours_per_shift, working_days_per_year, planned_maintenance_hours_per_year,
    capacity_utilization_rate, accessories_cost_percentage, installation_cost_percentage,
    payback_period_years, interest_rate_percentage, insurance_rate_percentage,
    machine_footprint_sqm, rent_per_sqm_per_month, maintenance_cost_percentage,
    power_kwh_per_hour, electricity_cost_per_kwh, admin_overhead_percentage, profit_margin_percentage,
    power_kw, currency, currency_symbol,
    direct_overhead_rate, indirect_overhead_rate, usd_lhr_total,
    direct_overhead_source, indirect_overhead_source, labor_rate_source,
    economics_version, economics_updated_at,
    capability_source, benchmark_source_key,
    benchmark_direct_overhead_rate_usd_hr, benchmark_indirect_overhead_rate_usd_hr, benchmark_labor_rate_usd_hr
  )
  SELECT
    NULL, NULL,
    'USA', 'Sheet Metal', 'Sheet Metal', NULL,
    tp.raw->>'name',
    tp.raw->>'description',
    tp.raw->>'machine_manufacturer_location',
    NULLIF(tp.raw->>'machine_price_usd', '')::numeric,
    GREATEST(COALESCE(NULLIF(tp.raw->>'machine_price_usd', '')::numeric, 1), 1),
    true,
    ROUND(COALESCE(NULLIF(tp.raw->>'direct_overhead_rate_usd_hr','')::numeric,0) + COALESCE(NULLIF(tp.raw->>'indirect_overhead_rate_usd_hr','')::numeric,0), 2),
    ROUND(COALESCE(NULLIF(tp.raw->>'direct_overhead_rate_usd_hr','')::numeric,0) + COALESCE(NULLIF(tp.raw->>'indirect_overhead_rate_usd_hr','')::numeric,0), 2),
    ROUND(COALESCE(NULLIF(tp.raw->>'direct_overhead_rate_usd_hr','')::numeric,0) + COALESCE(NULLIF(tp.raw->>'indirect_overhead_rate_usd_hr','')::numeric,0), 2),
    3, 8, 260, 0,
    95, 6, 20, 10, 8, 1, 0, 0, 6, 0, 0, 0, 0,
    NULLIF(tp.raw->>'machine_power_kw', '')::numeric,
    'USD', '$',
    NULLIF(tp.raw->>'direct_overhead_rate_usd_hr', '')::numeric,
    NULLIF(tp.raw->>'indirect_overhead_rate_usd_hr', '')::numeric,
    NULLIF(tp.raw->>'labor_rate_usd_hr', '')::numeric,
    'benchmark', 'benchmark', 'benchmark',
    1, NOW(),
    'benchmark', tp.key,
    NULLIF(tp.raw->>'direct_overhead_rate_usd_hr', '')::numeric,
    NULLIF(tp.raw->>'indirect_overhead_rate_usd_hr', '')::numeric,
    NULLIF(tp.raw->>'labor_rate_usd_hr', '')::numeric
  FROM to_promote tp;

  GET DIAGNOSTICS matched_count = ROW_COUNT;
  RAISE NOTICE 'Migration 585: promoted % new mhr_records row(s) for Standard Press (expect 4).', matched_count;
END $$;

-- Step 3: Link process taxonomy identity only (machine_class deliberately
-- left NULL -- see header; matches migration 572's precedent exactly).
UPDATE mhr_records SET process_route = 'Bending/Floating /Forming', operation = 'Std Press'
WHERE benchmark_source_key LIKE 'Standard Press:%' AND process_route IS NULL;

-- Step 4: Backfill Tier-1 universal economics fields (migration 573's exact UPDATE)
UPDATE mhr_records m
SET
  labor_time_standard = COALESCE(m.labor_time_standard, (srd.raw->>'labor_time_standard')::numeric),
  avg_utilization = COALESCE(m.avg_utilization, (srd.raw->>'avg_utilization')::numeric),
  good_part_yield = COALESCE(m.good_part_yield, (srd.raw->>'good_part_yield')::numeric),
  machine_length_mm = COALESCE(m.machine_length_mm, (srd.raw->>'machine_length_mm')::numeric),
  machine_width_mm = COALESCE(m.machine_width_mm, (srd.raw->>'machine_width_mm')::numeric),
  machine_life_yr = COALESCE(m.machine_life_yr, (srd.raw->>'machine_life_yr')::numeric),
  machine_power_kw = COALESCE(m.machine_power_kw, (srd.raw->>'machine_power_kw')::numeric),
  machine_uptime_pct = COALESCE(m.machine_uptime_pct, (srd.raw->>'machine_uptime_pct')::numeric),
  annual_maintenance_factor_pct = COALESCE(m.annual_maintenance_factor_pct, (srd.raw->>'annual_maintenance_factor_pct')::numeric),
  footprint_allowance_factor = COALESCE(m.footprint_allowance_factor, (srd.raw->>'footprint_allowance_factor')::numeric),
  installation_factor_pct = COALESCE(m.installation_factor_pct, (srd.raw->>'installation_factor_pct')::numeric)
FROM sm_reference_data srd
WHERE srd.key = m.benchmark_source_key
  AND srd.category = 'machine'
  AND srd.key LIKE 'Standard Press:%';

-- Salvage value / supplies-cost-per-year (migration 574 columns, feed Step 6's formula)
UPDATE mhr_records m
SET
  salvage_value_factor_pct = COALESCE(m.salvage_value_factor_pct, (srd.raw->>'salvage_value_factor_pct')::numeric),
  supplies_cost_per_year = COALESCE(m.supplies_cost_per_year, (srd.raw->>'supplies_cost_usd_yr')::numeric)
FROM sm_reference_data srd
WHERE srd.key = m.benchmark_source_key
  AND srd.category = 'machine'
  AND srd.key LIKE 'Standard Press:%';

-- Step 5: Backfill wage_grade/operators/setup_time_hr (wage_grade stays NULL
-- -- genuinely absent in the source, not fabricated; operators/setup_time_hr
-- ARE present and backfilled).
UPDATE mhr_records m
SET
  wage_grade = COALESCE(m.wage_grade, NULLIF(srd.raw->>'wage_grade_name', '')),
  operators = COALESCE(m.operators, (srd.raw->>'number_of_operators')::numeric),
  setup_time_hr = COALESCE(m.setup_time_hr, (srd.raw->>'setup_time_hr')::numeric)
FROM sm_reference_data srd
WHERE srd.key = m.benchmark_source_key
  AND srd.category = 'machine'
  AND srd.key LIKE 'Standard Press:%';

-- Step 6: Backfill calculated_mhr_usd_hr / mhr_source (migration 580's exact UPDATE)
UPDATE mhr_records
SET
  legacy_imported_mhr_usd_hr = manual_mhr_value,
  calculated_mhr_usd_hr = ROUND(
    (
      machine_price_usd * (1 - CASE WHEN salvage_value_factor_pct > 1 THEN salvage_value_factor_pct / 100 ELSE salvage_value_factor_pct END) / machine_life_yr
      + machine_price_usd * CASE WHEN annual_maintenance_factor_pct > 1 THEN annual_maintenance_factor_pct / 100 ELSE annual_maintenance_factor_pct END
      + machine_price_usd * CASE WHEN installation_factor_pct > 1 THEN installation_factor_pct / 100 ELSE installation_factor_pct END / machine_life_yr
      + COALESCE(supplies_cost_per_year, 0)
    )
    /
    (
      6240 * CASE WHEN machine_uptime_pct > 1 THEN machine_uptime_pct / 100 ELSE machine_uptime_pct END * avg_utilization
    ),
    4
  ),
  mhr_source = 'calculated'
WHERE benchmark_source_key IS NOT NULL
  AND calculated_mhr_usd_hr IS NULL
  AND machine_price_usd IS NOT NULL AND machine_price_usd > 0
  AND machine_life_yr IS NOT NULL AND machine_life_yr > 0
  AND salvage_value_factor_pct IS NOT NULL
  AND annual_maintenance_factor_pct IS NOT NULL
  AND installation_factor_pct IS NOT NULL
  AND machine_uptime_pct IS NOT NULL AND machine_uptime_pct > 0
  AND avg_utilization IS NOT NULL AND avg_utilization > 0
  AND benchmark_source_key LIKE 'Standard Press:%';

COMMIT;

-- Verification (run manually after):
-- SELECT machine_name, machine_class, process_route, operation, direct_overhead_rate,
--        indirect_overhead_rate, total_machine_hour_rate, calculated_mhr_usd_hr, wage_grade, operators
--   FROM mhr_records WHERE benchmark_source_key LIKE 'Standard Press:%' ORDER BY machine_name;
-- -- Should return exactly 4 rows (the generic press-force tiers), not 16.
-- SELECT count(*) FROM sm_reference_data WHERE category='machine' AND key LIKE 'Standard Press:%';
-- -- Should return 16 (all staged, regardless of promotion dedup).
-- SELECT count(*) FROM sm_reference_data WHERE category='machine' AND key LIKE 'Standard Press (staging):%';
-- -- Should return 16 (Step 1b's separate audit copy of press_machine_staging.json -- never promoted).
