-- ============================================================================
-- Migration 619 seed: raw_materials.cure_time_min (Injection Molding Phase 1)
-- Generated by gen_619_seed_material_cure_time.js -- DO NOT hand-edit, re-run
-- the generator and diff instead.
--
-- 33 of 35 real cureTimeMin materials matched to a live
-- raw_materials row by grade-code suffix (e.g. "CF50", "GF10-FR"). See
-- 619_unmatched_materials.json for any that didn't match -- a real gap to
-- review, not silently dropped.
--
-- Run AFTER migration 619's ALTER TABLE has been applied.
-- ============================================================================

BEGIN;

UPDATE raw_materials SET cure_time_min = 30 WHERE id = '84e02520-db27-414e-bb01-ae0a7f32a0d1'; -- Generic Unsaturated Polyester (UP-CF50) (source: Unsaturated Polyester, CF50)
UPDATE raw_materials SET cure_time_min = 30 WHERE id = '4c4f1fa5-bf25-4907-be76-67b59d78e17b'; -- Generic Unsaturated Polyester (UP-CF53) (source: Unsaturated Polyester, CF53)
UPDATE raw_materials SET cure_time_min = 30 WHERE id = 'c88a0972-78f3-42c3-a9bd-e653fc40ed24'; -- Generic Unsaturated Polyester (UP-CF55) (source: Unsaturated Polyester, CF55)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = 'fe9e7db4-add6-4e70-95cf-d6d2f832f564'; -- Generic Unsaturated Polyester (UP-GF10-FR) (source: Unsaturated Polyester, GF10-FR)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = '163623cf-c1b6-4ae9-bdcb-0d65add7a7bc'; -- Generic Unsaturated Polyester (UP-GF10-FRLS) (source: Unsaturated Polyester, GF10-FRLS)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = '1905cd45-285c-41a5-8d27-6ba84adcec7e'; -- Generic Unsaturated Polyester (UP-GF12-FR) (source: Unsaturated Polyester, GF12-FR)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = '97ecd9bb-b0f9-4340-ae48-651a687750e7'; -- Generic Unsaturated Polyester (UP-GF15-FR) (source: Unsaturated Polyester, GF15-FR)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = 'dc8bc4e7-7c35-41b1-b005-382dce361cd1'; -- Generic Unsaturated Polyester (UP-GF15-FRLS) (source: Unsaturated Polyester, GF15-FRLS)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = '12fed754-dfa0-457d-979b-5d6d1da3a22d'; -- Generic Unsaturated Polyester (UP-GF15-LS) (source: Unsaturated Polyester, GF15-LS)
UPDATE raw_materials SET cure_time_min = 30 WHERE id = '9ded8b93-f251-40eb-a4c0-c1093b3d33aa'; -- Generic Unsaturated Polyester (UP-GF15-SR) (source: Unsaturated Polyester, GF15-SR)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = '6db8799b-37a2-4048-8ed9-e0893876bc6c'; -- Generic Unsaturated Polyester (UP-GF18-FR) (source: Unsaturated Polyester, GF18-FR)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = 'c8bd5021-c0af-452a-a6c5-371fb8d7591f'; -- Generic Unsaturated Polyester (UP-GF20-FR) (source: Unsaturated Polyester, GF20-FR)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = 'a40acd2d-64d1-4e09-923b-9957e05c09a0'; -- Generic Unsaturated Polyester (UP-GF20-FRLS) (source: Unsaturated Polyester, GF20-FRLS)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = '4b8675f0-a192-41bb-8e00-12ffb27f35df'; -- Generic Unsaturated Polyester (UP-GF20-LS) (source: Unsaturated Polyester, GF20-LS)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = '2f79bf70-2e84-4391-852a-1cf97c80ca32'; -- Generic Unsaturated Polyester (UP-GF22-FR) (source: Unsaturated Polyester, GF22-FR)
UPDATE raw_materials SET cure_time_min = 40 WHERE id = '11d13e21-6a85-40f2-9686-f9a964fbc487'; -- Generic Unsaturated Polyester (UP-GF24-GP) (source: Unsaturated Polyester, GF24-GP)
UPDATE raw_materials SET cure_time_min = 30 WHERE id = 'c7370bfd-57f4-4530-90f8-b6117197c385'; -- Generic Unsaturated Polyester (UP-GF25-FR) (source: Unsaturated Polyester, GF25-FR)
UPDATE raw_materials SET cure_time_min = 30 WHERE id = '1bcb8d53-068b-4c2e-9c04-07ba24fdb33e'; -- Generic Unsaturated Polyester (UP-GF25-GA) (source: Unsaturated Polyester, GF25-GA)
UPDATE raw_materials SET cure_time_min = 30 WHERE id = 'db097316-14a5-4664-9275-bb36bbf48f1f'; -- Generic Unsaturated Polyester (UP-GF25-LS) (source: Unsaturated Polyester, GF25-LS)
UPDATE raw_materials SET cure_time_min = 40 WHERE id = 'f918e928-4e44-412e-86c1-f0fc1da74cd6'; -- Generic Unsaturated Polyester (UP-GF27-LPA) (source: Unsaturated Polyester, GF27-LPA)
UPDATE raw_materials SET cure_time_min = 30 WHERE id = '79543325-d57a-41b6-879e-fbd847eef72d'; -- Generic Unsaturated Polyester (UP-GF28-GP) (source: Unsaturated Polyester, GF28-GP)
UPDATE raw_materials SET cure_time_min = 40 WHERE id = '71315f02-6478-4e43-8ce4-0e90c3d1fe1e'; -- Generic Unsaturated Polyester (UP-GF28-LD) (source: Unsaturated Polyester, GF28-LD)
UPDATE raw_materials SET cure_time_min = 40 WHERE id = 'c6baf4e0-69a1-4558-9696-fc46a38c8d09'; -- Generic Unsaturated Polyester (UP-GF30-LP) (source: Unsaturated Polyester, GF30-LP)
UPDATE raw_materials SET cure_time_min = 30 WHERE id = '5fe44ecb-63e8-4b05-b67c-746e840e6a49'; -- Generic Unsaturated Polyester (UP-GF30-LPA) (source: Unsaturated Polyester, GF30-LPA)
UPDATE raw_materials SET cure_time_min = 40 WHERE id = '0e67cf39-06de-4c16-852c-c8cecc590ba3'; -- Generic Unsaturated Polyester (UP-GF30-LS) (source: Unsaturated Polyester, GF30-LS)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = 'a1001f43-dba0-46b2-9483-83f615ca22b8'; -- Generic Unsaturated Polyester (UP-GF33-GP) (source: Unsaturated Polyester, GF33-GP)
UPDATE raw_materials SET cure_time_min = 30 WHERE id = '054d4208-4b13-4c1a-ae19-b5713a14f459'; -- Generic Unsaturated Polyester (UP-GF38-LPA) (source: Unsaturated Polyester, GF38-LPA)
UPDATE raw_materials SET cure_time_min = 30 WHERE id = '53ddf048-1ac3-4333-9ac4-7f95d0c48e2c'; -- Generic Unsaturated Polyester (UP-GF45-GP) (source: Unsaturated Polyester, GF45-GP)
UPDATE raw_materials SET cure_time_min = 40 WHERE id = '1636b982-d481-4e13-960e-14fbfcce847b'; -- Generic Unsaturated Polyester (UP-GF63-GP) (source: Unsaturated Polyester, GF63-GP)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = 'b4a57fb1-ee60-4ec8-b516-f5e7df30579d'; -- Generic Unsaturated Polyester (UP-GF8-CA) (source: Unsaturated Polyester, GF8-CA)
UPDATE raw_materials SET cure_time_min = 30 WHERE id = '6f128f24-bff1-4e7b-af4a-4aa281ad355d'; -- Generic Unsaturated Polyester (UP-GFCF55) (source: Unsaturated Polyester, GFCF55)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = '55959c53-6516-4a2e-b949-c182bfc5c232'; -- Generic Vinyl Ester, CF50 (source: Vinyl Ester, CF50)
UPDATE raw_materials SET cure_time_min = 35 WHERE id = '6de162d3-28a8-49db-be9b-84dad727b157'; -- Generic Vinyl Ester, CF60 (source: Vinyl Ester, CF60)

COMMIT;

-- Verification (run manually after):
-- SELECT material, cure_time_min FROM raw_materials WHERE cure_time_min IS NOT NULL ORDER BY material;
-- -- Expect 33 rows.
