-- ============================================================================
-- Migration 635: Seed process_taxonomy_operations for Reaction Injection
-- Molding (26 real operations)
--
-- Generated by gen_635_seed_rim_taxonomy_operations.js from
-- memory/Injection/process/digital_factory_operations.json. The other 3
-- real Injection Molding processes (Compression Molding: 9, Injection
-- Molding: 26, Structural foam molding: 26) already have this data from the
-- original migration 609 seed pass -- Reaction Injection Molding was added
-- later (migration 634) and never got its own operations seeded until now.
-- ============================================================================

DO $$
DECLARE
    v_rim_id UUID;
BEGIN
    SELECT id INTO v_rim_id FROM process_taxonomy
    WHERE process_group = 'Injection Molding' AND process_name = 'Reaction Injection Molding';

    IF v_rim_id IS NULL THEN
        RAISE EXCEPTION 'process_taxonomy row for Reaction Injection Molding not found -- run migration 634 first.';
    END IF;

    IF EXISTS (SELECT 1 FROM process_taxonomy_operations WHERE canonical_process_id = v_rim_id) THEN
        RAISE NOTICE 'Reaction Injection Molding already has taxonomy operations -- skipping to avoid duplicates.';
        RETURN;
    END IF;

    INSERT INTO process_taxonomy_operations (canonical_process_id, operation_category, feature_type, raw_compound_string, notes)
    VALUES
  (v_rim_id, 'As Molded', 'ComboVoid', 'Reaction Injection Molding:As Molded//ComboVoid', NULL),
  (v_rim_id, 'As Molded', 'CurvedSurface', 'Reaction Injection Molding:As Molded//CurvedSurface', NULL),
  (v_rim_id, 'As Molded', 'CurvedWall', 'Reaction Injection Molding:As Molded//CurvedWall', NULL),
  (v_rim_id, 'As Molded', 'MultiStepHole', 'Reaction Injection Molding:As Molded//MultiStepHole', NULL),
  (v_rim_id, 'As Molded', 'PlanarFace', 'Reaction Injection Molding:As Molded//PlanarFace', NULL),
  (v_rim_id, 'As Molded', 'Rib', 'Reaction Injection Molding:As Molded//Rib', NULL),
  (v_rim_id, 'As Molded', 'SharpEdge', 'Reaction Injection Molding:As Molded//SharpEdge', NULL),
  (v_rim_id, 'As Molded', 'SimpleHole', 'Reaction Injection Molding:As Molded//SimpleHole', NULL),
  (v_rim_id, 'As Molded', 'Void', 'Reaction Injection Molding:As Molded//Void', NULL),
  (v_rim_id, 'ComboVoidLifter', 'ComboVoid', 'Reaction Injection Molding:ComboVoidLifter//ComboVoid', NULL),
  (v_rim_id, 'ComboVoidNoCore', 'ComboVoid', 'Reaction Injection Molding:ComboVoidNoCore//ComboVoid', NULL),
  (v_rim_id, 'ComboVoidSideCore', 'ComboVoid', 'Reaction Injection Molding:ComboVoidSideCore//ComboVoid', NULL),
  (v_rim_id, 'ComboVoidUnscrewMandrel', 'ComboVoid', 'Reaction Injection Molding:ComboVoidUnscrewMandrel//ComboVoid', NULL),
  (v_rim_id, 'HoleLifter', 'SimpleHole', 'Reaction Injection Molding:HoleLifter//SimpleHole', NULL),
  (v_rim_id, 'HoleNoCore', 'SimpleHole', 'Reaction Injection Molding:HoleNoCore//SimpleHole', NULL),
  (v_rim_id, 'HoleSideCore', 'SimpleHole', 'Reaction Injection Molding:HoleSideCore//SimpleHole', NULL),
  (v_rim_id, 'HoleUnscrewMandrel', 'SimpleHole', 'Reaction Injection Molding:HoleUnscrewMandrel//SimpleHole', NULL),
  (v_rim_id, 'Lifters', 'LifterBundle', 'Reaction Injection Molding:Lifters//LifterBundle', NULL),
  (v_rim_id, 'MstepLifter', 'MultiStepHole', 'Reaction Injection Molding:MstepLifter//MultiStepHole', NULL),
  (v_rim_id, 'MstepNoCore', 'MultiStepHole', 'Reaction Injection Molding:MstepNoCore//MultiStepHole', NULL),
  (v_rim_id, 'MstepSideCore', 'MultiStepHole', 'Reaction Injection Molding:MstepSideCore//MultiStepHole', NULL),
  (v_rim_id, 'MstepUnscrewMandrel', 'MultiStepHole', 'Reaction Injection Molding:MstepUnscrewMandrel//MultiStepHole', NULL),
  (v_rim_id, 'Slides', 'SlideBundle', 'Reaction Injection Molding:Slides//SlideBundle', NULL),
  (v_rim_id, 'VoidLifter', 'Void', 'Reaction Injection Molding:VoidLifter//Void', NULL),
  (v_rim_id, 'VoidNoCore', 'Void', 'Reaction Injection Molding:VoidNoCore//Void', NULL),
  (v_rim_id, 'VoidSideCore', 'Void', 'Reaction Injection Molding:VoidSideCore//Void', NULL);

    RAISE NOTICE 'Inserted 26 operations for Reaction Injection Molding.';
END $$;

NOTIFY pgrst, 'reload schema';
