-- ============================================================================
-- Migration 636: Injection Molding reference-data staging layer
--
-- Mirrors sm_reference_data (migration 479) exactly -- same "lossless
-- landing table" philosophy: captures every sourced value exactly as given,
-- with no judgment yet about which ones a calculator actually consumes.
-- Promotion into a real operational table happens in its own later,
-- reviewed migration that cites the source row here (same discipline as
-- Sheet Metal -- see e.g. migration 619 (cure_time_min), sourced from
-- materials_final.json, a sibling file to this domain reference data).
--
-- Separate table, not a shared one with the Sheet Metal one, matching this
-- session established domain-ownership discipline (sheet_metal /
-- machining / injection_molding / shared) -- sm_reference_data is a
-- Sheet-Metal-owned table by name and design; this is the Injection Molding
-- equivalent, not a cross-domain table.
--
-- Source: memory/Injection/variables/digital_factory_variables.json (303
-- named engineering constants) and memory/Injection/process/digital_
-- factory_processes_and_rates.json digitalFactory_aPrioriUSA section (21
-- named rate/tolerance/markup settings under its one "Default" profile, and
-- 7 tool/mold material property records). The Germany-labeled section
-- process to default-machine list is NOT re-staged here -- that data is
-- already correctly promoted into process_taxonomy.default_machine_name and
-- default_tool_shop_name (migrations 634 and the original 609 seed).
-- ============================================================================

CREATE TABLE IF NOT EXISTS im_reference_data (
    id              SERIAL PRIMARY KEY,
    category        VARCHAR(20) NOT NULL,   -- variable | rate_profile | tool_material
    source_region   VARCHAR(10) NOT NULL,   -- e.g. USA
    source_version  VARCHAR(20) NOT NULL,   -- e.g. 2026-03 (dated snapshot, no vendor name)
    key             TEXT NOT NULL,          -- variable, setting, or material name
    value           TEXT,                   -- primary value as a string (numeric/enum/bool all stored as text)
    unit_type       TEXT,                   -- e.g. Length, Currency, Temperature -- as given by the source
    notes           TEXT,                   -- source description of what the value controls
    raw             JSONB,                  -- full original row, for fidelity beyond the columns above
    imported_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS im_reference_data_key
  ON im_reference_data(category, source_region, source_version, key);

ALTER TABLE im_reference_data ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read" ON im_reference_data;
CREATE POLICY "Public read" ON im_reference_data FOR SELECT USING (true);

COMMENT ON TABLE im_reference_data IS 'Lossless staging landing zone for Injection Molding reference data (Variables, Rate Profile Settings, Tool Materials), one category+region+version at a time. Not consumed directly by any calculator -- see promotion migrations for what actually feeds live cost formulas. Mirrors sm_reference_data (migration 479).';

-- Seed data is migration 637 (generated by gen_637_seed_im_reference_data.js),
-- kept in its own file so this schema migration stays reviewable on its own.

NOTIFY pgrst, 'reload schema';
