-- ============================================================================
-- Migration 638: Machining reference-data staging layer
--
-- Mirrors sm_reference_data (migration 479) and im_reference_data
-- (migration 636) exactly -- same "lossless landing table" philosophy:
-- captures every sourced value exactly as given, with no judgment yet
-- about which ones a calculator actually consumes. Promotion into a real
-- operational table happens in its own later, reviewed migration that
-- cites the source row here.
--
-- Separate table, not a shared one with the Sheet Metal or Injection
-- Molding ones, matching this session established domain-ownership
-- discipline (sheet_metal / machining / injection_molding / shared).
--
-- Source: memory/machining/variables.json (264 named engineering
-- constants, same variableName/stringValue/unitTypeName/notes shape as
-- the sibling Sheet Metal and Injection Molding variable files).
-- ============================================================================

CREATE TABLE IF NOT EXISTS machining_reference_data (
    id              SERIAL PRIMARY KEY,
    category        VARCHAR(20) NOT NULL,   -- variable (only category sourced so far)
    source_region   VARCHAR(10) NOT NULL,   -- e.g. USA
    source_version  VARCHAR(20) NOT NULL,   -- e.g. 2026-03 (dated snapshot, no vendor name)
    key             TEXT NOT NULL,          -- variable name
    value           TEXT,                   -- primary value as a string (numeric/enum/bool all stored as text)
    unit_type       TEXT,                   -- e.g. Length, Time, Angle -- as given by the source
    notes           TEXT,                   -- source description of what the value controls
    raw             JSONB,                  -- full original row, for fidelity beyond the columns above
    imported_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS machining_reference_data_key
  ON machining_reference_data(category, source_region, source_version, key);

ALTER TABLE machining_reference_data ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read" ON machining_reference_data;
CREATE POLICY "Public read" ON machining_reference_data FOR SELECT USING (true);

COMMENT ON TABLE machining_reference_data IS 'Lossless staging landing zone for Machining reference data (Variables). Not consumed directly by any calculator -- see promotion migrations for what actually feeds live cost formulas. Mirrors sm_reference_data (migration 479) and im_reference_data (migration 636).';

-- Seed data is migration 639 (generated by gen_639_seed_machining_reference_data.js),
-- kept in its own file so this schema migration stays reviewable on its own.

NOTIFY pgrst, 'reload schema';
