-- ============================================================================
-- Migration 640: Seed machining_reference_data category = 'wage_grade'
-- (schema: migration 638)
--
-- Generated by gen_640_seed_machining_wage_grade.js.
-- Row count: 43 (memory/machining/wage_grade_associations.json,
-- processCount 43).
--
-- NOT promoted into any live table -- staging only. See the generator
-- script header for why (grade-scale incompatibility with this app's own
-- lhr_wage_benchmarks scale), same deliberate scope as migration 482.
-- ============================================================================

INSERT INTO machining_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('wage_grade', 'USA', '2026-03', $str$2 Axis Bar Feed Lathe with Sub Spindle$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"2 Axis Bar Feed Lathe with Sub Spindle","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$2 Axis Lathe$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"2 Axis Lathe","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$3 Axis Bar Feed Lathe with Sub Spindle$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"3 Axis Bar Feed Lathe with Sub Spindle","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$3 Axis Lathe$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"3 Axis Lathe","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$3 Axis Mill$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"3 Axis Mill","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$3 Axis Router$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"3 Axis Router","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$4 Axis Mill$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"4 Axis Mill","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$5 Axis Mill$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"5 Axis Mill","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$5 Axis Router$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"5 Axis Router","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Automated Deburr$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Automated Deburr","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Bench Operation$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Bench Operation","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Bevel Gear Cutting Machine$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Bevel Gear Cutting Machine","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Broach$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Broach","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Cylindrical Grinder$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Cylindrical Grinder","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$DeMask$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"DeMask","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Deep Bore Machine$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Deep Bore Machine","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Drill Press$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Drill Press","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Etch Cell$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Etch Cell","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Gun Drill$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Gun Drill","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Hob Machine$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Hob Machine","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Inspection$str$, $str$4 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Inspection","wageGrade":"4 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Internal Grinder$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Internal Grinder","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Jig Bore$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Jig Bore","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Jig Grind$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Jig Grind","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Manual Deburr$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Manual Deburr","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Mask Cure$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Mask Cure","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$MillTurn$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"MillTurn","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$No Cost Feature$str$, NULL, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"No Cost Feature","wageGrade":null}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Perimeter Cut$str$, NULL, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Perimeter Cut","wageGrade":null}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Profile Gear Grinder$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Profile Gear Grinder","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Reciprocating Surface Grinder$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Reciprocating Surface Grinder","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Rotary Surface Grinder$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Rotary Surface Grinder","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Scribe$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Scribe","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Shaper$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Shaper","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Shaver$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Shaver","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Simultaneous Turning$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Simultaneous Turning","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Special Inspection$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Special Inspection","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Spline Roller$str$, $str$4 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Spline Roller","wageGrade":"4 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Stock Prep Lathe$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Stock Prep Lathe","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Stock Prep Mill$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Stock Prep Mill","wageGrade":"5 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Threaded Wheel Gear Grinder$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Threaded Wheel Gear Grinder","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Use Stock Machining$str$, NULL, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Use Stock Machining","wageGrade":null}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-03', $str$Wire EDM$str$, $str$5 - Metal$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Wire EDM","wageGrade":"5 - Metal"}$jsonb$::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
