-- ============================================================================
-- Migration 641: Seed sm_reference_data category = 'wage_grade' — corrected
-- 2026-09 snapshot (schema: migration 479; original snapshot: migration 482)
--
-- Generated by gen_641_seed_sheet_metal_wage_grade_v2.js.
-- Row count: 24 (memory/sheetmetal/wages.png).
--
-- Does NOT delete or modify migration 482's rows -- see the generator
-- script header for the supersede-by-latest-source_version read-path
-- behavior in ProcessesService.getDomainVariables().
-- ============================================================================

INSERT INTO sm_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('wage_grade', 'USA', '2026-09', $str$2 Axis Router$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"2 Axis Router","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$2 Roll Bending$str$, $str$4 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"2 Roll Bending","wageGrade":"4 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$3 Roll Bending$str$, $str$4 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"3 Roll Bending","wageGrade":"4 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$3D Laser$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"3D Laser","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$4 Roll Bending$str$, $str$4 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"4 Roll Bending","wageGrade":"4 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Bend Brake$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Bend Brake","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$CTL$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"CTL","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Deslag$str$, $str$2 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Deslag","wageGrade":"2 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Fiber Laser Cut$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Fiber Laser Cut","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Generic Press$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Generic Press","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Laser Cut$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Laser Cut","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Laser Punch$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Laser Punch","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Material Stock$str$, $str$0 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Material Stock","wageGrade":"0 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$No Cost Feature$str$, NULL, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"No Cost Feature","wageGrade":null}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$OxyFuel Cut$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"OxyFuel Cut","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Plasma Cut$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Plasma Cut","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Plasma Punch$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Plasma Punch","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Progressive Die$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Progressive Die","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Shear$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Shear","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Std Press$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Std Press","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Tandem Press$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Tandem Press","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Turret Press$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Turret Press","wageGrade":"3 - Metal"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$User-Defined Process$str$, NULL, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"User-Defined Process","wageGrade":null}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Waterjet Cut$str$, $str$3 - Metal$str$, NULL, $str$Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).$str$, $jsonb${"process":"Waterjet Cut","wageGrade":"3 - Metal"}$jsonb$::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
