-- ============================================================================
-- Migration 642: Seed im_reference_data category = 'wage_grade'
-- (schema: migration 636)
--
-- Generated by gen_642_seed_im_wage_grade.js.
-- Row count: 6 (memory/Injection/wagegrade.png).
--
-- NOT promoted into any live table -- staging only. See the generator
-- script header for why, same deliberate scope as migration 482/640.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
('wage_grade', 'USA', '2026-09', $str$Compression Molding$str$, $str$1 - Plastic$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Compression Molding","wageGrade":"1 - Plastic"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Injection Molding$str$, $str$3 - Plastic$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Injection Molding","wageGrade":"3 - Plastic"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$No Cost Feature$str$, NULL, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"No Cost Feature","wageGrade":null}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Reaction Injection Molding$str$, $str$3 - Plastic$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Reaction Injection Molding","wageGrade":"3 - Plastic"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$Structural Foam Molding$str$, $str$3 - Plastic$str$, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"Structural Foam Molding","wageGrade":"3 - Plastic"}$jsonb$::jsonb),
('wage_grade', 'USA', '2026-09', $str$User-Defined Process$str$, NULL, NULL, $str$Process -> required labour grade$str$, $jsonb${"process":"User-Defined Process","wageGrade":null}$jsonb$::jsonb)
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
