SELECT rm.material, rm.material_grade, rm.ultimate_tensile_strength AS uts,
       rm.yield_tensile_strength AS yts, rm.hardness_system, rm.cost_usa, rm.created_at
FROM raw_materials rm
JOIN (VALUES
  ('Generic Aluminum, AA 1100'),
  ('Generic Aluminum, AA 2219'),
  ('Generic Aluminum, AA 3105'),
  ('Generic Aluminum, AA 383.0'),
  ('Generic Aluminum, AA 7003'),
  ('Generic Aluminum, ANSI 1050A'),
  ('Generic Aluminum, ANSI 2007'),
  ('Generic Aluminum, ANSI 2017'),
  ('Generic Aluminum, ANSI 2024'),
  ('Generic Aluminum, ANSI 2030'),
  ('Generic Aluminum, ANSI 3003'),
  ('Generic Aluminum, ANSI 3103'),
  ('Generic Aluminum, ANSI 5005'),
  ('Generic Aluminum, ANSI 5005A'),
  ('Generic Aluminum, ANSI 5019'),
  ('Generic Aluminum, ANSI 5052'),
  ('Generic Aluminum, ANSI 5083'),
  ('Generic Aluminum, ANSI 5119'),
  ('Generic Aluminum, ANSI 5251'),
  ('Generic Aluminum, ANSI 5454'),
  ('Generic Aluminum, ANSI 5754'),
  ('Generic Aluminum, ANSI 6012'),
  ('Generic Aluminum, ANSI 6060'),
  ('Generic Aluminum, ANSI 6061'),
  ('Generic Aluminum, ANSI 6082'),
  ('Generic Aluminum, ANSI 7020'),
  ('Generic Aluminum, ANSI 7022'),
  ('Generic Aluminum, ANSI 7050'),
  ('Generic Aluminum, ANSI 7075'),
  ('Generic Brass, UNS C36000'),
  ('Generic C60'),
  ('Generic C60E'),
  ('Generic Copper, UNS C11000'),
  ('Generic Copper, UNS C18150'),
  ('Generic Copper, UNS C27200'),
  ('Generic Copper, UNS C28000'),
  ('Generic Copper, UNS C51900'),
  ('Generic Copper, UNS C62730'),
  ('Generic Galv. Steel, Hot Worked, AISI 1010'),
  ('Generic Galv. Steel, Hot Worked, AISI 1012'),
  ('Generic Galv. Steel, Hot Worked, AISI 1020'),
  ('Generic Galv. Steel, Hot Worked, DX51D'),
  ('Generic Galv. Steel, Hot Worked, DX54'),
  ('Generic Hastelloy C-276'),
  ('Generic Hastelloy X'),
  ('Generic Haynes alloy 230'),
  ('Generic Inconel 625'),
  ('Generic Inconel 718'),
  ('Generic Stainless Steel, 15-5PH'),
  ('Generic Stainless Steel, 17-4PH'),
  ('Generic Stainless Steel, 440B'),
  ('Generic Stainless Steel, A240'),
  ('Generic Stainless Steel, A351 CF8'),
  ('Generic Stainless Steel, AISI 301'),
  ('Generic Stainless Steel, AISI 303'),
  ('Generic Stainless Steel, AISI 304'),
  ('Generic Stainless Steel, AISI 304L'),
  ('Generic Stainless Steel, AISI 316'),
  ('Generic Stainless Steel, AISI 316L'),
  ('Generic Stainless Steel, AISI 316Ti'),
  ('Generic Stainless Steel, AISI 321'),
  ('Generic Stainless Steel, AISI 441'),
  ('Generic Steel, AISI 1035'),
  ('Generic Steel, AISI 4140, Medium-Carbon'),
  ('Generic Steel, Cold Worked, AISI 1005'),
  ('Generic Steel, Cold Worked, AISI 1008'),
  ('Generic Steel, Cold Worked, AISI 1010'),
  ('Generic Steel, Cold Worked, AISI 1012'),
  ('Generic Steel, Cold Worked, AISI 1018'),
  ('Generic Steel, Cold Worked, AISI 1020'),
  ('Generic Steel, Cold Worked, AISI 1050'),
  ('Generic Steel, Cold Worked, AISI 4130'),
  ('Generic Steel, Cold Worked, AISI 4340'),
  ('Generic Steel, Cold Worked, AISI 5210'),
  ('Generic Steel, Cold Worked, AISI 8620'),
  ('Generic Steel, Cold Worked, DC06'),
  ('Generic Steel, Hot Worked, AISI 1006'),
  ('Generic Steel, Hot Worked, AISI 1008'),
  ('Generic Steel, Hot Worked, AISI 1010'),
  ('Generic Steel, Hot Worked, AISI 1012'),
  ('Generic Steel, Hot Worked, AISI 1018'),
  ('Generic Steel, Hot Worked, AISI 1020'),
  ('Generic Steel, Hot Worked, AISI 1042'),
  ('Generic Steel, Hot Worked, AISI 1045'),
  ('Generic Steel, Hot Worked, AISI 1049'),
  ('Generic Steel, Hot Worked, AISI 1050'),
  ('Generic Steel, Hot Worked, AISI 1075'),
  ('Generic Steel, Hot Worked, AISI 1095'),
  ('Generic Steel, Hot Worked, AISI 1213'),
  ('Generic Steel, Hot Worked, AISI 12L13'),
  ('Generic Steel, Hot Worked, AISI 1513'),
  ('Generic Steel, Hot Worked, AISI 4140'),
  ('Generic Steel, Hot Worked, AISI 4140H'),
  ('Generic Steel, Hot Worked, AISI 5115'),
  ('Generic Steel, Hot Worked, AISI 6150'),
  ('Generic Steel, Hot Worked, ASTM A36'),
  ('Generic Steel, Hot Worked, ASTM A572 Grade 50'),
  ('Generic Steel, Hot Worked, Grade S235JR')
) AS names(material) ON rm.material = names.material
ORDER BY rm.material;