// One-off generator for migration 619's seed data. Not part of the schema
// migration itself -- run manually to produce the SQL, inspect the diff,
// then commit. Same discipline as every other gen_*.js script (offline,
// file-in/file-out, no live DB credentials -- matches against a checked-in
// snapshot of raw_materials instead).
//
// GROUND TRUTH: memory/Injection/materials_final.json's real cureTimeMin
// field (35 materials, all Unsaturated Polyester / Vinyl Ester SMC/BMC
// compression-molding materials, real values 30-40 min) matched against
// 619_live_raw_materials_snapshot.json (a verbatim export of the live
// raw_materials table, 2026-09-02).
//
// MATCHING: materials_final.json names its materials
// "Unsaturated Polyester, CF50" / "Vinyl Ester, CF60"; raw_materials names
// the SAME real materials "Generic Unsaturated Polyester (UP-CF50)" /
// "Generic Vinyl Ester, CF60" -- different formatting, same real grade code
// suffix ("CF50", "GF10-FR", ...). Confirmed exactly 35 raw_materials rows
// match /polyester|vinyl ester/i, the same count as materials_final's 35
// real cureTimeMin rows.
//
// MUST match on (family, code) together, not code alone: an earlier version
// of this script keyed by code suffix only and silently matched
// "Unsaturated Polyester, CF50" (materials_final) to "Generic Vinyl Ester,
// CF50" (raw_materials) -- two DIFFERENT real material families that happen
// to share the same composition-code suffix. Caught by reading the
// generated SQL's own inline provenance comments before use, not by any
// automated check -- always read a generator's output, not just its exit
// code.
const fs = require('fs');
const path = require('path');

const SCRIPTS_DIR = __dirname;
const REPO_ROOT = path.join(__dirname, '..', '..', '..');

const materialsFinal = JSON.parse(
  fs.readFileSync(path.join(REPO_ROOT, 'memory', 'Injection', 'materials_final.json'), 'utf8'),
).materials;
const rawMaterialsSnapshot = JSON.parse(
  fs.readFileSync(path.join(SCRIPTS_DIR, '619_live_raw_materials_snapshot.json'), 'utf8'),
).rows;

function sqlStr(v) {
  return v === null || v === undefined || v === '' ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;
}

// "Unsaturated Polyester, CF50" -> { family: "UNSATURATED POLYESTER", code: "CF50" }
function familyAndCodeFromMaterialsFinal(name) {
  const parts = name.split(',');
  if (parts.length < 2) return null;
  return { family: parts[0].trim().toUpperCase(), code: parts[1].trim().toUpperCase() };
}

// raw_materials uses two real, different naming conventions for these
// families (confirmed live, not a guess): Unsaturated Polyester rows are
// parenthetical ("Generic Unsaturated Polyester (UP-CF50)" -> family
// "UNSATURATED POLYESTER", code "CF50"); Vinyl Ester rows are comma-
// separated ("Generic Vinyl Ester, CF60" -> family "VINYL ESTER", code
// "CF60", the same convention materials_final.json itself uses). Try both;
// a name matching neither is left genuinely unmatched, not guessed. Always
// strips the leading "Generic " prefix so the family string is directly
// comparable to materials_final's own family name.
function familyAndCodeFromRawMaterials(name) {
  const stripped = (name || '').replace(/^Generic\s+/i, '');
  const parenMatch = /^(.+?)\s*\(([A-Z]{2})-(.+)\)\s*$/.exec(stripped);
  if (parenMatch) return { family: parenMatch[1].trim().toUpperCase(), code: parenMatch[3].toUpperCase() };
  const commaParts = stripped.split(',');
  if (commaParts.length > 1) return { family: commaParts[0].trim().toUpperCase(), code: commaParts[1].trim().toUpperCase() };
  return null;
}

// Keyed by "FAMILY||CODE" -- both must match together, never code alone
// (see this module's own header comment for the real bug this fixed).
const rawByFamilyAndCode = new Map();
for (const r of rawMaterialsSnapshot) {
  const fc = familyAndCodeFromRawMaterials(r.material);
  if (fc) rawByFamilyAndCode.set(`${fc.family}||${fc.code}`, r);
}

const withCureTime = materialsFinal.filter(
  (m) => m.processingParameters && m.processingParameters.cureTimeMin != null,
);

const matched = [];
const unmatched = [];
for (const m of withCureTime) {
  const fc = familyAndCodeFromMaterialsFinal(m.primaryId);
  const rawRow = fc ? rawByFamilyAndCode.get(`${fc.family}||${fc.code}`) : null;
  if (rawRow) {
    matched.push({ rawId: rawRow.id, rawName: rawRow.material, sourceName: m.primaryId, cureTimeMin: m.processingParameters.cureTimeMin });
  } else {
    unmatched.push({ sourceName: m.primaryId, familyAndCode: fc });
  }
}

const sql = `-- ============================================================================
-- Migration 619 seed: raw_materials.cure_time_min (Injection Molding Phase 1)
-- Generated by gen_619_seed_material_cure_time.js -- DO NOT hand-edit, re-run
-- the generator and diff instead.
--
-- ${matched.length} of ${withCureTime.length} real cureTimeMin materials matched to a live
-- raw_materials row by grade-code suffix (e.g. "CF50", "GF10-FR"). See
-- 619_unmatched_materials.json for any that didn't match -- a real gap to
-- review, not silently dropped.
--
-- Run AFTER migration 619's ALTER TABLE has been applied.
-- ============================================================================

BEGIN;

${matched.map((m) => `UPDATE raw_materials SET cure_time_min = ${m.cureTimeMin} WHERE id = ${sqlStr(m.rawId)}; -- ${m.rawName} (source: ${m.sourceName})`).join('\n')}

COMMIT;

-- Verification (run manually after):
-- SELECT material, cure_time_min FROM raw_materials WHERE cure_time_min IS NOT NULL ORDER BY material;
-- -- Expect ${matched.length} rows.
`;

fs.writeFileSync(path.join(SCRIPTS_DIR, '..', '619_seed_material_cure_time.sql'), sql, 'utf8');
fs.writeFileSync(path.join(SCRIPTS_DIR, '619_unmatched_materials.json'), JSON.stringify(unmatched, null, 2), 'utf8');

console.log('Wrote 619_seed_material_cure_time.sql --', matched.length, 'of', withCureTime.length, 'real cureTimeMin materials matched.');
console.log('Wrote 619_unmatched_materials.json --', unmatched.length, 'unmatched (needs review).');
