// Generator: seeds sm_reference_data (migration 479's schema) with a NEW,
// corrected snapshot of category = 'wage_grade' -- source_version '2026-09'
// -- transcribed from memory/sheetmetal/wages.png (a real Digital Factory
// screenshot the user supplied 2026-09-02), superseding migration 482's
// original '2026-03' wage_grade batch for any process name both share.
//
// Migration 482's rows are NOT deleted (lossless staging -- every sourced
// snapshot stays in the table as history). Instead, ProcessesService.
// getDomainVariables() prefers the newest source_version per (category,
// key) when the same key appears in more than one snapshot, so this
// corrected batch is what the Process page's Variables section shows.
//
// wages.png has real, confirmed differences from 482's set (482 has
// 'CO Laser'/'Deburr'/'Slit Press'; this screenshot has '3D Laser'/
// 'Deslag'/'Std Press' instead) -- the user confirmed treating this
// screenshot as the corrected/superseding source rather than a merge.
//
// 'No Cost Feature' and 'User-Defined Process' carry no real grade in the
// source (not real machining/forming processes) -- stored as NULL, not
// fabricated, matching the same two placeholder rows' treatment in
// Machining's migration 640.
//
// Dollar-quoting for all free-text fields -- see gen_637's header for why.

const fs = require('fs');
const path = require('path');

const OUT_SQL = path.join(__dirname, '../641_seed_sheet_metal_wage_grade_v2.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-09';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

// Transcribed directly from memory/sheetmetal/wages.png, top to bottom.
const PROCESSES = [
  ['2 Axis Router', '3 - Metal'],
  ['2 Roll Bending', '4 - Metal'],
  ['3 Roll Bending', '4 - Metal'],
  ['3D Laser', '3 - Metal'],
  ['4 Roll Bending', '4 - Metal'],
  ['Bend Brake', '3 - Metal'],
  ['CTL', '2 - Metal'],
  ['Deslag', '2 - Metal'],
  ['Fiber Laser Cut', '3 - Metal'],
  ['Generic Press', '3 - Metal'],
  ['Laser Cut', '3 - Metal'],
  ['Laser Punch', '3 - Metal'],
  ['Material Stock', '0 - Metal'],
  ['No Cost Feature', null],
  ['OxyFuel Cut', '3 - Metal'],
  ['Plasma Cut', '3 - Metal'],
  ['Plasma Punch', '3 - Metal'],
  ['Progressive Die', '3 - Metal'],
  ['Shear', '3 - Metal'],
  ['Std Press', '3 - Metal'],
  ['Tandem Press', '3 - Metal'],
  ['Turret Press', '3 - Metal'],
  ['User-Defined Process', null],
  ['Waterjet Cut', '3 - Metal'],
];

const rows = PROCESSES.map(([processName, wageGrade]) => ({
  category: 'wage_grade',
  key: processName,
  value: wageGrade,
  unit_type: null,
  notes: 'Process -> required labour grade (2026-09 corrected snapshot, supersedes migration 482 for shared process names).',
  raw: { process: processName, wageGrade },
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 641: Seed sm_reference_data category = 'wage_grade' — corrected
-- 2026-09 snapshot (schema: migration 479; original snapshot: migration 482)
--
-- Generated by gen_641_seed_sheet_metal_wage_grade_v2.js.
-- Row count: ${rows.length} (memory/sheetmetal/wages.png).
--
-- Does NOT delete or modify migration 482's rows -- see the generator
-- script header for the supersede-by-latest-source_version read-path
-- behavior in ProcessesService.getDomainVariables().
-- ============================================================================

INSERT INTO sm_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
