// Generator: seeds im_reference_data (migration 636's schema) from the real
// Injection Molding reference data files. Three categories:
//
//   'variable'      <- memory/Injection/variables/digital_factory_variables.json
//                      (303 named engineering constants — same shape as
//                      sm_reference_data's own 'variable' category)
//   'rate_profile'  <- digital_factory_processes_and_rates.json's
//                      digitalFactory_aPrioriUSA.settings (21 named rate/
//                      tolerance/markup fields under the source's one
//                      "Default" profile)
//   'tool_material' <- digital_factory_processes_and_rates.json's
//                      digitalFactory_aPrioriUSA.toolMaterials (7 real
//                      tool/mold material property records — a genuinely
//                      multi-column structure, not a flat name/value pair;
//                      `value` holds materialCostUsdPerKg as the single
//                      most load-bearing number, `raw` preserves every
//                      other property losslessly, matching sm_reference_
//                      data's own "raw JSONB for full fidelity" design)
//
// source_region/source_version: 'USA' / '2026-03', matching sm_reference_
// data's own already-established real values for the sibling licensed
// reference dataset (same snapshot family, same neutral non-vendor label).
//
// Offline, file-in/file-out — matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const VARS_FILE = path.join(__dirname, '../../../memory/Injection/variables/digital_factory_variables.json');
const RATES_FILE = path.join(__dirname, '../../../memory/Injection/process/digital_factory_processes_and_rates.json');
const OUT_SQL = path.join(__dirname, '../637_seed_im_reference_data.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

// Dollar-quoting instead of standard '...' escaping: a real source note can
// end with a nested-quoted phrase (e.g. "...in case of 'Standard Mold
// Base'"), which standard escaping turns into 3 consecutive single quotes
// at the string boundary ('''). That is unambiguous to real Postgres, but
// several SQL editors (including the one used to run these migrations)
// apparently do their own naive client-side quote-tracking that this
// pattern desyncs, producing misleading errors on a LATER, unrelated
// statement. Dollar-quoting needs no internal escaping at all, so this
// class of bug cannot recur regardless of what the source text contains.
function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const rows = [];

// ── category = 'variable' ────────────────────────────────────────────────
const varsData = JSON.parse(fs.readFileSync(VARS_FILE, 'utf8'));
for (const v of varsData.digitalFactoryVariables) {
  rows.push({
    category: 'variable',
    key: v.variableName,
    value: v.stringValue,
    unit_type: v.unitTypeName || null,
    notes: v.notes || null,
    raw: v,
  });
}

// ── category = 'rate_profile' ────────────────────────────────────────────
const ratesData = JSON.parse(fs.readFileSync(RATES_FILE, 'utf8'));
const settings = ratesData.digitalFactory_aPrioriUSA.settings;
for (const [field, val] of Object.entries(settings)) {
  if (field === 'name' || field === 'description') continue; // metadata, not a rate value
  rows.push({
    category: 'rate_profile',
    key: field,
    value: String(val),
    unit_type: null,
    notes: `From the "${settings.name}" rate profile (digitalFactory_aPrioriUSA.settings).`,
    raw: { profileName: settings.name, field, value: val },
  });
}

// ── category = 'tool_material' ───────────────────────────────────────────
const toolMaterials = ratesData.digitalFactory_aPrioriUSA.toolMaterials;
for (const m of toolMaterials) {
  rows.push({
    category: 'tool_material',
    key: m.name,
    value: m.materialCostUsdPerKg != null ? String(m.materialCostUsdPerKg) : null,
    unit_type: 'Currency/kg',
    notes: `${m.materialTypeName} tool/mold material — hardness ${m.hardness}, machinability index ${m.machinabilityIndex}.`,
    raw: m,
  });
}

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const counts = rows.reduce((acc, r) => { acc[r.category] = (acc[r.category] || 0) + 1; return acc; }, {});

const sql = `-- ============================================================================
-- Migration 637: Seed im_reference_data (schema: migration 636)
--
-- Generated by gen_637_seed_im_reference_data.js.
-- Row counts: ${Object.entries(counts).map(([k, v]) => `${k}=${v}`).join(', ')} (total ${rows.length}).
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows (${JSON.stringify(counts)}) to ${OUT_SQL}`);
