// Generator: seeds machining_reference_data (migration 638's schema) with
// category = 'wage_grade' from memory/machining/wage_grade_associations.json
// (43 real process -> required labour grade associations).
//
// Same category/shape as sm_reference_data's own 'wage_grade' rows
// (migration 482): key = process name, value = wage grade name exactly as
// given by the source (no reformatting -- lossless staging), raw = full
// {process, wageGrade} pair. Landed into the SAME reference-data staging
// table migration 638/639 created for Machining 'variable' rows, not a
// separate table -- matching migration 482's own "same table, new
// category" precedent for Sheet Metal.
//
// NOT promoted into any live table here -- same deliberate staging-only
// scope as migration 482 (see that migration's header: the source grade
// scale is a different, incompatible numbering from this app's own
// lhr_wage_benchmarks scale; promotion is a separate, later, reviewed
// decision once a real consumer needs it).
//
// source_region/source_version: 'USA' / '2026-03', matching every sibling
// reference-data seed this session (479, 636/637, 638/639).
//
// Dollar-quoting for all free-text fields -- see gen_637's header for why.
//
// Offline, file-in/file-out -- matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const WAGE_GRADE_FILE = path.join(__dirname, '../../../memory/machining/wage_grade_associations.json');
const OUT_SQL = path.join(__dirname, '../640_seed_machining_wage_grade.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const data = JSON.parse(fs.readFileSync(WAGE_GRADE_FILE, 'utf8'));

const rows = data.processes.map((p) => ({
  category: 'wage_grade',
  key: p.processName,
  value: p.wageGradeName || null,
  unit_type: null,
  notes: 'Process -> required labour grade',
  raw: { process: p.processName, wageGrade: p.wageGradeName || null },
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 640: Seed machining_reference_data category = 'wage_grade'
-- (schema: migration 638)
--
-- Generated by gen_640_seed_machining_wage_grade.js.
-- Row count: ${rows.length} (memory/machining/wage_grade_associations.json,
-- processCount ${data.processCount}).
--
-- NOT promoted into any live table -- staging only. See the generator
-- script header for why (grade-scale incompatibility with this app's own
-- lhr_wage_benchmarks scale), same deliberate scope as migration 482.
-- ============================================================================

INSERT INTO machining_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
