// Generator: seeds process_taxonomy_operations for Reaction Injection
// Molding — confirmed live (2026-09-02) to be the only one of the 4 real
// Injection Molding processes with zero rows in this table (Compression
// Molding has 9, Injection Molding has 26, Structural foam molding has 26 —
// all already seeded by the original migration 609 pass; Reaction Injection
// Molding was added later, migration 634, and never got this treatment).
//
// Source: memory/Injection/process/digital_factory_operations.json's
// `operations` array, filtered to `process === "Reaction Injection Molding"`
// (26 real entries — the same feature-type taxonomy shape as Injection
// Molding's own 26, both being molding processes with equivalent tooling
// features: lifters/slides/side-cores/unscrew-mandrel mechanisms).
//
// canonical_process_id is looked up live by process_name (not hardcoded) —
// matches this session's established no-hardcoded-identity discipline.

const fs = require('fs');
const path = require('path');

const OPS_FILE = path.join(__dirname, '../../../memory/Injection/process/digital_factory_operations.json');
const OUT_SQL = path.join(__dirname, '../635_seed_rim_taxonomy_operations.sql');

const data = JSON.parse(fs.readFileSync(OPS_FILE, 'utf8'));
const rimOps = data.operations.filter((o) => o.process === 'Reaction Injection Molding');

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
}

const valuesSql = rimOps.map((o) => {
  return `  (v_rim_id, ${sqlStr(o.operationCategory)}, ${sqlStr(o.featureType)}, ${sqlStr(o.processName)}, ${sqlStr(o.notes)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 635: Seed process_taxonomy_operations for Reaction Injection
-- Molding (${rimOps.length} real operations)
--
-- Generated by gen_635_seed_rim_taxonomy_operations.js from
-- memory/Injection/process/digital_factory_operations.json. The other 3
-- real Injection Molding processes (Compression Molding: 9, Injection
-- Molding: 26, Structural foam molding: 26) already have this data from the
-- original migration 609 seed pass -- Reaction Injection Molding was added
-- later (migration 634) and never got its own operations seeded until now.
-- ============================================================================

DO $$
DECLARE
    v_rim_id UUID;
BEGIN
    SELECT id INTO v_rim_id FROM process_taxonomy
    WHERE process_group = 'Injection Molding' AND process_name = 'Reaction Injection Molding';

    IF v_rim_id IS NULL THEN
        RAISE EXCEPTION 'process_taxonomy row for Reaction Injection Molding not found -- run migration 634 first.';
    END IF;

    IF EXISTS (SELECT 1 FROM process_taxonomy_operations WHERE canonical_process_id = v_rim_id) THEN
        RAISE NOTICE 'Reaction Injection Molding already has taxonomy operations -- skipping to avoid duplicates.';
        RETURN;
    END IF;

    INSERT INTO process_taxonomy_operations (canonical_process_id, operation_category, feature_type, raw_compound_string, notes)
    VALUES
${valuesSql};

    RAISE NOTICE 'Inserted ${rimOps.length} operations for Reaction Injection Molding.';
END $$;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rimOps.length} real operations to ${OUT_SQL}`);
