// Generator: seeds machining_reference_data (migration 638's schema) from
// the real Machining reference data file.
//
//   'variable'  <- memory/machining/variables.json (264 named engineering
//                  constants -- same shape as sm_reference_data's and
//                  im_reference_data's own 'variable' category)
//
// source_region/source_version: 'USA' / '2026-03', matching the already-
// established real values used for the sibling licensed reference
// datasets (sm_reference_data migration 479, im_reference_data migration
// 637 -- same snapshot family, same neutral non-vendor label).
//
// Dollar-quoting (not standard '...' escaping) for all free-text fields --
// see gen_637_seed_im_reference_data.js's header comment for why: a real
// source note can end on its own embedded quoted phrase, which standard
// apostrophe-doubling turns into 3+ consecutive single quotes at the
// string boundary. That is unambiguous to real Postgres but breaks some
// SQL editors' client-side statement-splitting. Dollar-quoting needs no
// escaping at all, so this class of bug cannot recur here regardless of
// what the source text contains.
//
// Offline, file-in/file-out -- matches every other gen_*.js in this codebase.

const fs = require('fs');
const path = require('path');

const VARS_FILE = path.join(__dirname, '../../../memory/machining/variables.json');
const OUT_SQL = path.join(__dirname, '../639_seed_machining_reference_data.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-03';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

const rows = [];

const varsData = JSON.parse(fs.readFileSync(VARS_FILE, 'utf8'));
for (const v of varsData.variables) {
  rows.push({
    category: 'variable',
    key: v.variableName,
    value: v.stringValue,
    unit_type: v.unitTypeName || null,
    notes: v.notes || null,
    raw: v,
  });
}

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const counts = rows.reduce((acc, r) => { acc[r.category] = (acc[r.category] || 0) + 1; return acc; }, {});

const sql = `-- ============================================================================
-- Migration 639: Seed machining_reference_data (schema: migration 638)
--
-- Generated by gen_639_seed_machining_reference_data.js.
-- Row counts: ${Object.entries(counts).map(([k, v]) => `${k}=${v}`).join(', ')} (total ${rows.length}).
-- ============================================================================

INSERT INTO machining_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows (${JSON.stringify(counts)}) to ${OUT_SQL}`);
