// Generator: seeds im_reference_data (migration 636's schema) with
// category = 'wage_grade' -- transcribed from memory/Injection/wagegrade.png
// (a real Digital Factory screenshot the user supplied 2026-09-02), with
// Compression Molding and Reaction Injection Molding's values (hidden
// behind collapsed tree rows in the screenshot) confirmed directly by the
// user rather than guessed.
//
// Same category/shape as sm_reference_data's own 'wage_grade' rows
// (migration 482) and machining_reference_data's (migration 640): key =
// process name, value = wage grade name exactly as given by the source
// (no reformatting), raw = full {process, wageGrade} pair.
//
// 'No Cost Feature' and 'User-Defined Process' carry no real grade in the
// source (not real molding processes) -- stored as NULL, not fabricated,
// matching the same two placeholder rows' treatment in Machining's
// migration 640 and Sheet Metal's migration 641.
//
// NOT promoted into any live table here -- same deliberate staging-only
// scope as migration 482/640 (grade-scale reconciliation against this
// app's own lhr_wage_benchmarks scale is a separate, later decision).
//
// source_region/source_version: 'USA' / '2026-09' (screenshot captured
// this session, distinct from the older '2026-03' JSON-file-sourced
// im_reference_data 'variable'/'rate_profile'/'tool_material' batch).
//
// Dollar-quoting for all free-text fields -- see gen_637's header for why.

const fs = require('fs');
const path = require('path');

const OUT_SQL = path.join(__dirname, '../642_seed_im_wage_grade.sql');

const SOURCE_REGION = 'USA';
const SOURCE_VERSION = '2026-09';

function sqlStr(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return `$str$${String(v)}$str$`;
}
function sqlJsonb(obj) {
  return `$jsonb$${JSON.stringify(obj)}$jsonb$::jsonb`;
}

// From memory/Injection/wagegrade.png, with Compression Molding / Reaction
// Injection Molding values confirmed directly by the user (2026-09-02).
const PROCESSES = [
  ['Compression Molding', '1 - Plastic'],
  ['Injection Molding', '3 - Plastic'],
  ['No Cost Feature', null],
  ['Reaction Injection Molding', '3 - Plastic'],
  ['Structural Foam Molding', '3 - Plastic'],
  ['User-Defined Process', null],
];

const rows = PROCESSES.map(([processName, wageGrade]) => ({
  category: 'wage_grade',
  key: processName,
  value: wageGrade,
  unit_type: null,
  notes: 'Process -> required labour grade',
  raw: { process: processName, wageGrade },
}));

const valuesSql = rows.map((r) => {
  return `('${r.category}', '${SOURCE_REGION}', '${SOURCE_VERSION}', ${sqlStr(r.key)}, ${sqlStr(r.value)}, ${sqlStr(r.unit_type)}, ${sqlStr(r.notes)}, ${sqlJsonb(r.raw)})`;
}).join(',\n');

const sql = `-- ============================================================================
-- Migration 642: Seed im_reference_data category = 'wage_grade'
-- (schema: migration 636)
--
-- Generated by gen_642_seed_im_wage_grade.js.
-- Row count: ${rows.length} (memory/Injection/wagegrade.png).
--
-- NOT promoted into any live table -- staging only. See the generator
-- script header for why, same deliberate scope as migration 482/640.
-- ============================================================================

INSERT INTO im_reference_data (category, source_region, source_version, key, value, unit_type, notes, raw) VALUES
${valuesSql}
ON CONFLICT (category, source_region, source_version, key) DO NOTHING;

NOTIFY pgrst, 'reload schema';
`;

fs.writeFileSync(OUT_SQL, sql, 'utf8');
console.log(`Wrote ${rows.length} rows to ${OUT_SQL}`);
